<?php

return [
    'admin' => [
        [
            'category' => 'Data Siswa dan Excel',
            'question' => 'Bagaimana import siswa dari Excel?',
            'answer' => 'Buka menu Siswa, unduh template terbaru, isi data sesuai kolom, lalu unggah file. Pastikan tahun ajaran aktif benar dan nama kelas di Excel sama dengan kelas yang sudah dibuat. Jika ada baris gagal, perbaiki file lalu unggah ulang.',
            'keywords' => ['import siswa', 'upload siswa', 'unggah siswa', 'excel', 'xls', 'xlsx', 'template', 'kelas', 'baris gagal'],
        ],
        [
            'category' => 'Data Pengajar',
            'question' => 'Bagaimana reset password guru?',
            'answer' => 'Buka detail atau edit pengajar, cari bagian keamanan password, lalu pilih Reset password guru. Admin membuat password sementara tanpa melihat password lama. Setelah login, guru wajib mengganti password tersebut.',
            'keywords' => ['reset password', 'lupa password', 'ganti password', 'password sementara', 'wajib ganti', 'tidak bisa login', 'password lama'],
        ],
        [
            'category' => 'Tanda Tangan Digital',
            'question' => 'Bagaimana upload tanda tangan wali kelas?',
            'answer' => 'Buka Edit Pengajar, lalu gunakan kartu Tanda Tangan Digital. Pilih gambar tanda tangan guru wali kelas dan tunggu sampai muncul pesan berhasil. Tanda tangan dipakai saat guru tersebut menjadi wali kelas pada rapor.',
            'keywords' => ['ttd', 'tanda tangan', 'signature', 'upload tanda tangan', 'gambar tanda tangan', 'wali kelas', 'png'],
        ],
        [
            'category' => 'Tahun Ajaran dan Kelas',
            'question' => 'Bagaimana berpindah ke semester genap?',
            'answer' => 'Gunakan proses transisi semester setelah data semester ganjil selesai dicek. Sistem menyiapkan struktur semester genap dan mempertahankan riwayat semester ganjil. Setelah selesai, cek kelas, mapel, dan daftar siswa.',
            'keywords' => ['semester genap', 'transisi', 'ganjil', 'genap', 'tahun ajaran', 'kelas baru', 'semester baru'],
        ],
        [
            'category' => 'Rapor dan Template',
            'question' => 'Mengapa PDF belum berubah setelah data diperbarui?',
            'answer' => 'File PDF/DOCX yang sudah dibuat bisa masih menampilkan hasil lama. Buka preview untuk mengecek data terbaru, lalu buat ulang atau unduh ulang rapor setelah nilai, capaian, catatan, atau tanda tangan diperbarui.',
            'keywords' => ['pdf belum berubah', 'rapor belum berubah', 'docx', 'preview', 'download', 'unduh', 'buat ulang', 'tanda tangan baru'],
        ],
        [
            'category' => 'Progress dan Troubleshooting',
            'question' => 'Apa arti progress penginputan?',
            'answer' => 'Progress menunjukkan seberapa lengkap data yang dibutuhkan pada tahun ajaran dan semester aktif. Nilai, TP/LM, siswa, dan data pendukung dapat memengaruhi hasilnya. Jika tidak berubah, cek konteks semester dan kelengkapan input.',
            'keywords' => ['progress', 'penginputan', 'dashboard', 'nilai', 'belum 100', 'semester', 'otomatis diperbarui'],
        ],
        [
            'category' => 'Data Siswa dan Excel',
            'question' => 'Bagaimana mengunduh template Excel siswa?',
            'answer' => 'Buka menu Siswa lalu pilih unduh template import. Template terbaru berisi kolom yang harus diisi, contoh data aman, dan daftar kelas pada tahun ajaran aktif.',
            'keywords' => ['download template', 'unduh template', 'template siswa', 'excel', 'xlsx', 'daftar kelas'],
        ],
        [
            'category' => 'Data Siswa dan Excel',
            'question' => 'Mengapa harus memakai template terbaru?',
            'answer' => 'Template terbaru mengikuti aturan import saat ini. Kelas harus sudah ada, format tanggal harus benar, dan NIS/NISN harus unik. Template lama atau contoh bebas bisa menyebabkan file ditolak.',
            'keywords' => ['template terbaru', 'template lama', 'file contoh', 'excel', 'format', 'nis', 'nisn'],
        ],
        [
            'category' => 'Data Siswa dan Excel',
            'question' => 'Bagaimana mengisi template Excel siswa?',
            'answer' => 'Isi satu baris untuk satu siswa. Gunakan format tanggal lahir YYYY-MM-DD, jenis kelamin L atau P, dan nama kelas persis seperti daftar kelas pada sheet template. Jangan mengubah nama kolom.',
            'keywords' => ['isi template', 'tanggal lahir', 'yyyy-mm-dd', 'jenis kelamin', 'l', 'p', 'kelas'],
        ],
        [
            'category' => 'Data Siswa dan Excel',
            'question' => 'Kolom apa yang wajib diisi saat import siswa?',
            'answer' => 'Isi minimal data identitas utama yang diminta template, terutama NIS, NISN, nama, tanggal lahir, jenis kelamin, agama, alamat, kelas, dan data orang tua yang tersedia. Jika ada kolom wajib kosong, import akan ditolak.',
            'keywords' => ['kolom wajib', 'nis', 'nisn', 'nama', 'tanggal lahir', 'agama', 'alamat', 'orang tua'],
        ],
        [
            'category' => 'Data Siswa dan Excel',
            'question' => 'Mengapa file Excel ditolak?',
            'answer' => 'Biasanya karena kolom tidak sesuai template, tanggal tidak valid, NIS/NISN duplikat, kelas tidak ditemukan, atau ada file yang bukan Excel. Baca pesan baris yang muncul, perbaiki file, lalu unggah ulang.',
            'keywords' => ['file ditolak', 'excel ditolak', 'validasi', 'tanggal salah', 'duplikat', 'kelas tidak ditemukan'],
        ],
        [
            'category' => 'Data Siswa dan Excel',
            'question' => 'Mengapa kelas tidak ditemukan saat import?',
            'answer' => 'Kelas di file harus sudah dibuat pada tahun ajaran aktif dan penulisannya harus sama. Cek daftar kelas di template atau menu Kelas, lalu samakan kolom kelas pada file Excel.',
            'keywords' => ['kelas tidak ditemukan', 'kelas salah', 'import siswa', 'tahun ajaran aktif', 'daftar kelas'],
        ],
        [
            'category' => 'Data Siswa dan Excel',
            'question' => 'Apa yang terjadi jika kelas pada file tidak sesuai?',
            'answer' => 'Import akan dibatalkan agar data tidak masuk ke kelas yang salah. Perbaiki nama kelas pada file atau buat kelas yang benar terlebih dahulu, lalu unggah ulang.',
            'keywords' => ['kelas tidak sesuai', 'kelas salah', 'baris gagal', 'import dibatalkan', 'unggah ulang'],
        ],
        [
            'category' => 'Data Siswa dan Excel',
            'question' => 'Apakah siswa otomatis masuk kelas dan semester aktif?',
            'answer' => 'Ya. Jika import berhasil, siswa akan terdaftar pada kelas, tahun ajaran, dan semester aktif sesuai file. Data lama tidak dibuat ganda bila NIS/NISN sudah terdeteksi duplikat.',
            'keywords' => ['otomatis masuk kelas', 'semester aktif', 'tahun ajaran aktif', 'kelas aktif', 'siswa terdaftar'],
        ],
        [
            'category' => 'Data Siswa dan Excel',
            'question' => 'Apakah import dapat membuat siswa ganda?',
            'answer' => 'Sistem menolak NIS atau NISN yang sudah ada, termasuk duplikat di dalam file yang sama. Jika muncul pesan duplikat, periksa data siswa lama dan baris Excel terkait.',
            'keywords' => ['siswa ganda', 'data ganda', 'duplikat', 'nis duplikat', 'nisn duplikat'],
        ],
        [
            'category' => 'Data Siswa dan Excel',
            'question' => 'Apa yang harus dilakukan jika sebagian baris gagal?',
            'answer' => 'Jika ada satu baris bermasalah, import tidak menyimpan sebagian data. Perbaiki semua baris yang disebutkan pada pesan error, lalu unggah ulang file yang sudah bersih.',
            'keywords' => ['sebagian baris gagal', 'baris gagal', 'import gagal', 'error baris', 'unggah ulang'],
        ],
        [
            'category' => 'Data Siswa dan Excel',
            'question' => 'Apakah file contoh atau template lama masih boleh digunakan?',
            'answer' => 'Sebaiknya tidak. Gunakan template terbaru dari sistem agar kolom, format tanggal, dan daftar kelas sesuai tahun ajaran aktif. File contoh lama bisa tidak cocok dengan aturan sekarang.',
            'keywords' => ['template lama', 'file contoh', 'contoh excel', 'template terbaru', 'aturan import'],
        ],
        [
            'category' => 'Data Siswa dan Excel',
            'question' => 'Bagaimana memeriksa hasil import siswa?',
            'answer' => 'Setelah import berhasil, buka Data Siswa dan filter kelas atau semester yang sedang aktif. Jika siswa belum terlihat, cek tahun ajaran aktif dan pastikan kelas pada file sudah benar.',
            'keywords' => ['hasil import', 'cek import', 'data siswa', 'filter kelas', 'siswa tidak muncul'],
        ],
        [
            'category' => 'Data Pengajar',
            'question' => 'Bagaimana menambah pengajar?',
            'answer' => 'Buka menu Pengajar lalu pilih Tambah Data. Isi identitas, username, password awal, jabatan, kelas wali jika ada, dan kelas mengajar jika guru mengajar mapel tertentu.',
            'keywords' => ['tambah pengajar', 'buat guru', 'akun guru', 'wali kelas', 'kelas mengajar', 'username'],
        ],
        [
            'category' => 'Data Pengajar',
            'question' => 'Bagaimana mengubah data pengajar?',
            'answer' => 'Buka menu Pengajar, pilih guru, lalu edit data yang perlu diperbaiki. Perubahan tanggung jawab guru memengaruhi pilihan wali kelas, mapel, dan akses guru.',
            'keywords' => ['edit pengajar', 'ubah guru', 'data guru', 'tanggung jawab', 'wali kelas', 'pengajar'],
        ],
        [
            'category' => 'Data Pengajar',
            'question' => 'Mengapa password lama tidak dapat dilihat?',
            'answer' => 'Password disimpan secara aman dan tidak bisa ditampilkan kembali. Jika guru lupa password, admin cukup membuat password sementara melalui reset password.',
            'keywords' => ['password lama', 'lihat password', 'password tidak terlihat', 'keamanan password', 'lupa password'],
        ],
        [
            'category' => 'Data Pengajar',
            'question' => 'Apa fungsi password sementara?',
            'answer' => 'Password sementara dipakai agar guru bisa login kembali setelah reset. Setelah berhasil login, guru akan diminta membuat password baru yang hanya diketahui guru tersebut.',
            'keywords' => ['password sementara', 'login awal', 'reset password', 'wajib ganti', 'password baru'],
        ],
        [
            'category' => 'Data Pengajar',
            'question' => 'Mengapa guru harus mengganti password setelah reset?',
            'answer' => 'Ini untuk keamanan akun. Password sementara hanya membantu guru masuk kembali, lalu guru harus menggantinya agar admin tidak perlu mengetahui password pribadi guru.',
            'keywords' => ['wajib ganti password', 'ganti password setelah reset', 'password sementara', 'keamanan akun'],
        ],
        [
            'category' => 'Data Pengajar',
            'question' => 'Apakah admin perlu mengetahui password lama guru?',
            'answer' => 'Tidak. Admin tidak membutuhkan password lama untuk reset. Admin hanya membuat password sementara baru, lalu guru menggantinya setelah login.',
            'keywords' => ['password lama', 'admin tahu password', 'reset tanpa password lama', 'password sementara'],
        ],
        [
            'category' => 'Data Pengajar',
            'question' => 'Apakah reset password mengubah username?',
            'answer' => 'Tidak. Reset password hanya mengubah password dan menandai guru agar mengganti password saat login berikutnya. Username, nama, dan tanggung jawab guru tidak berubah.',
            'keywords' => ['username', 'reset password', 'ubah username', 'akun guru', 'tanggung jawab'],
        ],
        [
            'category' => 'Data Pengajar',
            'question' => 'Bagaimana jika guru lupa password?',
            'answer' => 'Admin dapat membuka data pengajar dan melakukan reset password. Berikan password sementara kepada guru melalui cara yang aman, lalu minta guru login dan mengganti password.',
            'keywords' => ['guru lupa password', 'lupa password', 'reset guru', 'tidak bisa login', 'password sementara'],
        ],
        [
            'category' => 'Data Pengajar',
            'question' => 'Bagaimana jika guru tidak bisa login setelah reset?',
            'answer' => 'Pastikan guru memakai username yang benar dan password sementara terbaru. Jika masih gagal, reset ulang password dan cek apakah akun guru masih aktif.',
            'keywords' => ['tidak bisa login', 'gagal login', 'password sementara', 'username', 'akun aktif'],
        ],
        [
            'category' => 'Data Pengajar',
            'question' => 'Siapa yang dapat mengunggah tanda tangan guru?',
            'answer' => 'Pada fitur saat ini, hanya admin yang dapat mengunggah, mengganti, atau menghapus tanda tangan guru. Guru dan wali kelas tidak mengunggah tanda tangan sendiri.',
            'keywords' => ['upload tanda tangan', 'siapa upload', 'admin only', 'guru upload ttd', 'wali upload ttd'],
        ],
        [
            'category' => 'Tanda Tangan Digital',
            'question' => 'Bagaimana menghapus atau mengganti tanda tangan digital guru?',
            'answer' => 'Buka Edit Pengajar, gunakan kartu Tanda Tangan Digital, lalu pilih Ganti Tanda Tangan atau Hapus. Menghapus tanda tangan tidak menghapus data guru atau data rapor.',
            'keywords' => ['hapus tanda tangan', 'ganti tanda tangan', 'tanda tangan digital', 'edit pengajar', 'ttd'],
        ],
        [
            'category' => 'Tanda Tangan Digital',
            'question' => 'Format file tanda tangan apa yang didukung?',
            'answer' => 'Gunakan PNG, JPG, JPEG, atau WebP dengan ukuran maksimal 1 MB. PNG transparan direkomendasikan agar tanda tangan terlihat rapi di dokumen rapor.',
            'keywords' => ['format tanda tangan', 'png', 'jpg', 'jpeg', 'webp', '1 mb', 'gambar tanda tangan'],
        ],
        [
            'category' => 'Tanda Tangan Digital',
            'question' => 'Mengapa gambar tanda tangan terlihat kecil?',
            'answer' => 'Rapor menyesuaikan gambar agar tidak merusak tata letak template. Gunakan gambar tanda tangan yang bersih dengan area kosong secukupnya, lalu cek ulang hasil DOCX atau PDF.',
            'keywords' => ['tanda tangan kecil', 'gambar kecil', 'ukuran tanda tangan', 'docx', 'pdf'],
        ],
        [
            'category' => 'Tanda Tangan Digital',
            'question' => 'Mengapa PNG transparan direkomendasikan?',
            'answer' => 'PNG transparan biasanya terlihat lebih bersih di atas area tanda tangan rapor. JPG tetap bisa dipakai, tetapi latar belakang putih pada gambar mungkin ikut terlihat.',
            'keywords' => ['png transparan', 'background tanda tangan', 'latar belakang', 'jpg', 'gambar tanda tangan'],
        ],
        [
            'category' => 'Tanda Tangan Digital',
            'question' => 'Apakah tanda tangan wajib?',
            'answer' => 'Tidak wajib. Jika guru wali kelas belum memiliki tanda tangan, rapor tetap bisa dibuat dan area placeholder tanda tangan akan kosong.',
            'keywords' => ['tanda tangan wajib', 'opsional', 'tanpa tanda tangan', 'placeholder kosong', 'rapor tetap dibuat'],
        ],
        [
            'category' => 'Tanda Tangan Digital',
            'question' => 'Guru mana yang tanda tangannya dipakai pada rapor?',
            'answer' => 'Rapor memakai tanda tangan guru yang menjadi wali kelas untuk kelas, tahun ajaran, dan semester rapor tersebut. Guru mapel tidak dipakai sebagai tanda tangan wali.',
            'keywords' => ['guru tanda tangan', 'wali kelas', 'guru mapel', 'tanda tangan rapor', 'kelas semester'],
        ],
        [
            'category' => 'Tanda Tangan Digital',
            'question' => 'Apakah tanda tangan guru mapel ikut dipakai?',
            'answer' => 'Tidak. Placeholder tanda tangan wali kelas hanya memakai guru yang bertugas sebagai wali kelas pada konteks rapor. Guru mapel tetap tampil sesuai data mapel, tetapi tanda tangannya tidak dipakai.',
            'keywords' => ['guru mapel', 'tanda tangan guru mapel', 'ttd wali kelas', 'placeholder'],
        ],
        [
            'category' => 'Tanda Tangan Digital',
            'question' => 'Apa yang terjadi jika tanda tangan belum tersedia?',
            'answer' => 'Rapor tetap dapat dibuat. Bagian tanda tangan akan kosong, bukan error. Admin dapat mengunggah tanda tangan kapan saja sebelum membuat ulang dokumen rapor.',
            'keywords' => ['tanpa tanda tangan', 'ttd belum ada', 'placeholder kosong', 'rapor tetap berhasil'],
        ],
        [
            'category' => 'Tanda Tangan Digital',
            'question' => 'Mengapa rapor lama belum memakai tanda tangan baru?',
            'answer' => 'Dokumen rapor yang sudah dibuat sebelumnya menyimpan hasil lama. Setelah tanda tangan diganti, buat ulang atau unduh ulang rapor agar file baru memakai tanda tangan terbaru.',
            'keywords' => ['tanda tangan baru', 'rapor lama', 'pdf belum berubah', 'buat ulang', 'download ulang'],
        ],
        [
            'category' => 'Tanda Tangan Digital',
            'question' => 'Apakah rapor perlu dibuat ulang setelah tanda tangan diganti?',
            'answer' => 'Ya, jika ingin file DOCX/PDF menampilkan tanda tangan terbaru. Preview dapat membantu mengecek data, tetapi file lama tidak otomatis berubah.',
            'keywords' => ['buat ulang rapor', 'tanda tangan diganti', 'docx', 'pdf', 'file lama'],
        ],
        [
            'category' => 'Tanda Tangan Digital',
            'question' => 'Mengapa file SVG tidak diterima?',
            'answer' => 'SVG tidak diterima demi keamanan dan kestabilan dokumen. Gunakan PNG, JPG, JPEG, atau WebP dengan ukuran maksimal 1 MB.',
            'keywords' => ['svg ditolak', 'format tidak diterima', 'png', 'jpg', 'webp', 'keamanan'],
        ],
        [
            'category' => 'Tahun Ajaran dan Kelas',
            'question' => 'Bagaimana mengaktifkan tahun ajaran?',
            'answer' => 'Buka menu Tahun Ajaran lalu aktifkan tahun ajaran dan semester yang akan digunakan. Setelah aktif, data siswa, kelas, mapel, dan rapor mengikuti konteks tersebut.',
            'keywords' => ['aktifkan tahun ajaran', 'tahun ajaran aktif', 'semester aktif', 'ganjil', 'genap'],
        ],
        [
            'category' => 'Tahun Ajaran dan Kelas',
            'question' => 'Apa yang disalin saat transisi semester?',
            'answer' => 'Transisi semester menyiapkan struktur semester berikutnya seperti kelas, mapel, dan daftar siswa yang masih berada di kelas yang sama. Nilai dan data kerja semester lama tidak disalin sebagai nilai baru.',
            'keywords' => ['transisi semester', 'apa disalin', 'kelas', 'mapel', 'siswa', 'nilai lama'],
        ],
        [
            'category' => 'Tahun Ajaran dan Kelas',
            'question' => 'Mengapa kelas semester baru belum muncul?',
            'answer' => 'Cek apakah proses transisi sudah selesai dan tahun ajaran/semester yang benar sudah aktif. Jika masih belum muncul, ulangi pengecekan struktur atau hubungi pengelola sistem.',
            'keywords' => ['kelas belum muncul', 'semester baru', 'transisi', 'tahun ajaran aktif', 'kelas baru'],
        ],
        [
            'category' => 'Tahun Ajaran dan Kelas',
            'question' => 'Bagaimana melakukan kenaikan kelas?',
            'answer' => 'Kenaikan kelas dilakukan setelah semester genap selesai. Buat atau siapkan tahun ajaran berikutnya, cek rencana kenaikan kelas, pilih kelas tujuan yang benar, lalu proses siswa yang sudah siap.',
            'keywords' => ['kenaikan kelas', 'naik kelas', 'semester genap', 'tahun ajaran berikutnya', 'kelas tujuan'],
        ],
        [
            'category' => 'Tahun Ajaran dan Kelas',
            'question' => 'Apa bedanya transisi semester dan kenaikan kelas?',
            'answer' => 'Transisi semester memindahkan konteks dari ganjil ke genap dalam tahun ajaran yang sama. Kenaikan kelas memproses siswa ke tahun ajaran berikutnya setelah semester genap selesai.',
            'keywords' => ['transisi semester', 'kenaikan kelas', 'ganjil', 'genap', 'tahun ajaran berikutnya'],
        ],
        [
            'category' => 'Tahun Ajaran dan Kelas',
            'question' => 'Apakah data semester lama tetap tersimpan?',
            'answer' => 'Ya. Data semester lama tetap menjadi riwayat dan tidak dihapus saat semester berganti. Pastikan selalu memilih tahun ajaran dan semester yang benar saat mengecek data.',
            'keywords' => ['data lama', 'riwayat', 'semester lama', 'tidak terhapus', 'ganjil', 'genap'],
        ],
        [
            'category' => 'Tahun Ajaran dan Kelas',
            'question' => 'Mengapa siswa tidak tampil di kelas semester baru?',
            'answer' => 'Biasanya siswa belum terdaftar pada kelas semester baru, atau tahun ajaran/semester yang aktif belum sesuai. Cek hasil transisi atau kenaikan kelas, lalu perbaiki dari menu yang tersedia.',
            'keywords' => ['siswa tidak tampil', 'kelas semester baru', 'enrollment', 'transisi', 'kenaikan kelas'],
        ],
        [
            'category' => 'Tahun Ajaran dan Kelas',
            'question' => 'Apa yang harus dicek setelah transisi semester?',
            'answer' => 'Cek tahun ajaran aktif, daftar kelas, wali kelas, mapel, siswa per kelas, dan akses guru. Setelah itu guru dapat mulai mengisi data semester baru.',
            'keywords' => ['cek setelah transisi', 'semester genap', 'kelas', 'wali kelas', 'mapel', 'akses guru'],
        ],
        [
            'category' => 'Tahun Ajaran dan Kelas',
            'question' => 'Apakah kelas dan mapel perlu dibuat ulang manual?',
            'answer' => 'Jika memakai fitur transisi atau salin struktur tahun ajaran, struktur utama dapat disiapkan oleh sistem. Admin tetap perlu mengecek hasilnya dan melengkapi data yang belum sesuai.',
            'keywords' => ['kelas manual', 'mapel manual', 'salin struktur', 'transisi', 'tahun ajaran baru'],
        ],
        [
            'category' => 'Rapor dan Template',
            'question' => 'Bagaimana membuat rapor?',
            'answer' => 'Pastikan nilai, absensi, catatan, capaian, ekstrakurikuler, dan template sudah siap. Dari halaman rapor, pilih siswa dan jenis rapor, lalu buat atau unduh dokumen sesuai kebutuhan.',
            'keywords' => ['membuat rapor', 'buat rapor', 'nilai', 'absensi', 'catatan', 'template'],
        ],
        [
            'category' => 'Rapor dan Template',
            'question' => 'Bagaimana membuka preview rapor?',
            'answer' => 'Buka menu rapor, pilih siswa, lalu gunakan preview untuk melihat data terbaru sebelum mengunduh DOCX atau PDF. Preview membantu mengecek isi tanpa membuat file final.',
            'keywords' => ['preview rapor', 'rapor', 'lihat rapor', 'cek rapor', 'siswa'],
        ],
        [
            'category' => 'Rapor dan Template',
            'question' => 'Bagaimana mengunduh DOCX?',
            'answer' => 'Pastikan template Word aktif tersedia untuk kelas dan jenis rapor. Setelah data lengkap, pilih unduh DOCX pada halaman rapor.',
            'keywords' => ['docx', 'word', 'download docx', 'unduh docx', 'template word'],
        ],
        [
            'category' => 'Rapor dan Template',
            'question' => 'Bagaimana mengunduh PDF?',
            'answer' => 'Pastikan template aktif tersedia dan data rapor lengkap. Jika tombol PDF tersedia, gunakan unduh PDF. Jika tidak tersedia, cek template atau hubungi pengelola sistem.',
            'keywords' => ['pdf', 'download pdf', 'unduh pdf', 'template', 'tombol pdf'],
        ],
        [
            'category' => 'Rapor dan Template',
            'question' => 'Mengapa tombol PDF tidak tersedia?',
            'answer' => 'Biasanya template belum aktif untuk kelas atau jenis rapor yang dipilih, atau dokumen belum dapat dibuat. Cek template rapor, data siswa, dan kelengkapan nilai.',
            'keywords' => ['tombol pdf tidak tersedia', 'pdf tidak tersedia', 'template', 'docx', 'rapor'],
        ],
        [
            'category' => 'Rapor dan Template',
            'question' => 'Kapan rapor perlu dibuat ulang?',
            'answer' => 'Buat ulang rapor setelah ada perubahan penting seperti nilai, absensi, capaian, catatan, template, atau tanda tangan wali kelas. File lama tidak otomatis berubah.',
            'keywords' => ['buat ulang rapor', 'rapor perlu dibuat ulang', 'nilai berubah', 'capaian berubah', 'tanda tangan berubah'],
        ],
        [
            'category' => 'Rapor dan Template',
            'question' => 'Apa perbedaan preview, DOCX, PDF, dan cetak HTML?',
            'answer' => 'Preview menampilkan data terbaru di browser. DOCX adalah file Word dari template. PDF adalah hasil dokumen siap cetak. Cetak HTML dipakai untuk melihat atau mencetak dari browser jika tersedia.',
            'keywords' => ['preview', 'docx', 'pdf', 'html print', 'cetak', 'word'],
        ],
        [
            'category' => 'Rapor dan Template',
            'question' => 'Apakah laporan lama akan terhapus jika data guru berubah?',
            'answer' => 'Tidak otomatis. Perubahan data guru atau tanda tangan memengaruhi dokumen baru yang dibuat ulang. File lama yang sudah tersimpan tetap menjadi riwayat sampai ada tindakan khusus.',
            'keywords' => ['laporan lama', 'data guru berubah', 'tanda tangan berubah', 'riwayat rapor', 'file lama'],
        ],
        [
            'category' => 'Rapor dan Template',
            'question' => 'Apa yang harus dilakukan jika placeholder terlihat mentah?',
            'answer' => 'Cek template Word. Placeholder harus ditulis utuh, misalnya ${ttd_wali_kelas}, tanpa terpecah formatnya. Jika masih muncul mentah, perbaiki template lalu unggah ulang.',
            'keywords' => ['placeholder mentah', 'placeholder', '${ttd_wali_kelas}', 'template word', 'format template'],
        ],
        [
            'category' => 'Rapor dan Template',
            'question' => 'Bagaimana memeriksa template rapor?',
            'answer' => 'Buka Format Rapor, cek template aktif, kelas, tahun ajaran, semester, dan jenis rapor. Pastikan placeholder ditulis lengkap dan template sesuai kelas yang digunakan.',
            'keywords' => ['cek template rapor', 'format rapor', 'template aktif', 'placeholder', 'kelas'],
        ],
        [
            'category' => 'Rapor dan Template',
            'question' => 'Bagaimana menggunakan placeholder ${ttd_wali_kelas}?',
            'answer' => 'Tulis ${ttd_wali_kelas} secara utuh di template Word pada area tanda tangan wali kelas. Jangan menaruhnya di text box atau memformat sebagian karakter. Jika tanda tangan belum ada, area akan kosong.',
            'keywords' => ['${ttd_wali_kelas}', 'ttd_wali_kelas', 'placeholder tanda tangan', 'template word', 'tanda tangan wali'],
        ],
        [
            'category' => 'Progress dan Troubleshooting',
            'question' => 'Mengapa progress belum 100%?',
            'answer' => 'Biasanya masih ada siswa, mapel, TP/LM, atau nilai akhir yang belum lengkap pada semester aktif. Cek dashboard, data nilai, dan mapel yang belum selesai.',
            'keywords' => ['progress belum 100', 'belum lengkap', 'nilai', 'tp', 'lm', 'dashboard'],
        ],
        [
            'category' => 'Progress dan Troubleshooting',
            'question' => 'Data apa saja yang memengaruhi progress?',
            'answer' => 'Progress nilai dipengaruhi oleh siswa yang terdaftar, mapel, LM, TP, nilai per siswa, dan nilai akhir. Data pendukung rapor seperti absensi dan catatan juga perlu dicek sebelum rapor dibuat.',
            'keywords' => ['data progress', 'progress nilai', 'siswa', 'mapel', 'lm', 'tp', 'nilai akhir'],
        ],
        [
            'category' => 'Progress dan Troubleshooting',
            'question' => 'Mengapa progress berbeda antarsemester?',
            'answer' => 'Setiap semester memiliki data sendiri. Nilai dan siswa semester ganjil tidak otomatis dihitung sebagai progress semester genap. Pastikan konteks semester yang dilihat sudah benar.',
            'keywords' => ['progress berbeda', 'antarsemester', 'ganjil', 'genap', 'semester aktif'],
        ],
        [
            'category' => 'Progress dan Troubleshooting',
            'question' => 'Apakah progress otomatis diperbarui?',
            'answer' => 'Progress diperbarui berdasarkan data yang tersimpan. Jika baru mengubah data tetapi tampilan belum berubah, buka ulang halaman atau pastikan perubahan sudah benar-benar disimpan.',
            'keywords' => ['progress otomatis', 'progress tidak berubah', 'refresh', 'simpan data', 'dashboard'],
        ],
        [
            'category' => 'Progress dan Troubleshooting',
            'question' => 'Apa yang harus dicek jika progress tidak berubah?',
            'answer' => 'Cek tahun ajaran, semester, daftar siswa, TP/LM, dan nilai akhir. Jika semua sudah lengkap tetapi progress tetap tidak berubah, hubungi pengelola sistem.',
            'keywords' => ['progress tidak berubah', 'cek progress', 'tahun ajaran', 'semester', 'hubungi admin'],
        ],
    ],

    'pengajar' => [
        [
            'category' => 'Input Nilai',
            'question' => 'Bagaimana input nilai?',
            'answer' => 'Masuk sebagai pengajar, buka Data Nilai Pelajaran, pilih mata pelajaran, lalu isi nilai siswa sesuai TP/LM yang tersedia. Setelah semua nilai diperiksa, tekan simpan.',
            'keywords' => ['input nilai', 'nilai', 'simpan nilai', 'tp', 'lm', 'mata pelajaran', 'siswa'],
        ],
        [
            'category' => 'Input Nilai',
            'question' => 'Mengapa siswa tidak muncul di input nilai?',
            'answer' => 'Biasanya siswa belum terdaftar pada kelas dan semester mata pelajaran tersebut. Cek semester aktif dan mata pelajaran yang dipilih. Jika masih kosong, hubungi admin.',
            'keywords' => ['siswa tidak muncul', 'daftar siswa', 'kelas', 'semester', 'input nilai', 'enrollment'],
        ],
        [
            'category' => 'Login dan Role',
            'question' => 'Bagaimana mengganti password setelah reset admin?',
            'answer' => 'Login memakai password sementara dari admin. Sistem akan mengarahkan ke halaman ganti password. Isi password baru dan konfirmasi, lalu simpan agar dashboard bisa dibuka.',
            'keywords' => ['ganti password', 'reset password', 'password sementara', 'wajib ganti', 'tidak bisa login'],
        ],
        [
            'category' => 'TP dan Lingkup Materi',
            'question' => 'Bagaimana mengelola TP?',
            'answer' => 'Buka daftar mata pelajaran, pilih tombol Kelola TP, lalu tambahkan atau ubah Tujuan Pembelajaran pada Lingkup Materi yang sesuai. TP dipakai sebagai dasar pengisian nilai.',
            'keywords' => ['kelola tp', 'tujuan pembelajaran', 'tp', 'lingkup materi', 'lm', 'mapel'],
        ],
        [
            'category' => 'Progress',
            'question' => 'Apa arti progress nilai?',
            'answer' => 'Progress menunjukkan kelengkapan nilai untuk mata pelajaran yang menjadi tanggung jawab pengajar pada semester aktif. Jika semua siswa dan TP sudah lengkap, progress menjadi 100%.',
            'keywords' => ['progress nilai', 'progress', '100%', 'nilai lengkap', 'semester aktif'],
        ],
        [
            'category' => 'Login dan Role',
            'question' => 'Bagaimana memilih role pengajar?',
            'answer' => 'Setelah login, gunakan pilihan role pada profil jika tersedia. Pilih Pengajar untuk menginput nilai. Jika role tidak muncul, assignment guru perlu dicek oleh admin.',
            'keywords' => ['pilih role', 'role pengajar', 'ganti role', 'dropdown profil', 'assignment'],
        ],
        [
            'category' => 'Mata Pelajaran',
            'question' => 'Mengapa mata pelajaran tidak muncul?',
            'answer' => 'Biasanya guru belum ditugaskan mengajar mata pelajaran tersebut pada kelas dan semester aktif. Cek role yang dipilih, lalu hubungi admin jika mapel masih belum muncul.',
            'keywords' => ['mata pelajaran tidak muncul', 'mapel tidak muncul', 'pengajar', 'kelas', 'semester', 'admin'],
        ],
        [
            'category' => 'Mata Pelajaran',
            'question' => 'Bagaimana membuka daftar siswa?',
            'answer' => 'Buka mata pelajaran yang diampu, lalu pilih halaman input atau preview nilai. Daftar siswa mengikuti kelas mata pelajaran pada tahun ajaran dan semester aktif.',
            'keywords' => ['daftar siswa', 'buka siswa', 'mata pelajaran', 'kelas', 'semester', 'preview nilai'],
        ],
        [
            'category' => 'Input Nilai',
            'question' => 'Bagaimana menyimpan nilai?',
            'answer' => 'Isi nilai sesuai kolom yang tersedia, periksa kembali siswa dan TP, lalu tekan simpan. Tunggu pesan berhasil sebelum pindah halaman.',
            'keywords' => ['simpan nilai', 'nilai disimpan', 'input nilai', 'pesan berhasil', 'tp'],
        ],
        [
            'category' => 'Input Nilai',
            'question' => 'Mengapa nilai tidak dapat disimpan?',
            'answer' => 'Biasanya ada nilai yang belum valid, siswa tidak sesuai kelas mapel, atau TP/LM belum lengkap. Baca pesan yang muncul, perbaiki bagian tersebut, lalu simpan ulang.',
            'keywords' => ['nilai tidak dapat disimpan', 'gagal simpan', 'validasi nilai', 'tp', 'lm', 'kelas salah'],
        ],
        [
            'category' => 'TP dan Lingkup Materi',
            'question' => 'Apa fungsi Lingkup Materi?',
            'answer' => 'Lingkup Materi mengelompokkan materi utama pada mata pelajaran. Di dalamnya terdapat TP yang dipakai untuk menilai capaian belajar siswa.',
            'keywords' => ['lingkup materi', 'lm', 'fungsi lm', 'materi', 'tp', 'nilai'],
        ],
        [
            'category' => 'TP dan Lingkup Materi',
            'question' => 'Apa fungsi Tujuan Pembelajaran?',
            'answer' => 'Tujuan Pembelajaran atau TP adalah target belajar yang dinilai. Pastikan TP sudah tersedia sebelum menginput nilai agar progress dapat dihitung dengan benar.',
            'keywords' => ['tujuan pembelajaran', 'tp', 'fungsi tp', 'target belajar', 'progress'],
        ],
        [
            'category' => 'Progress',
            'question' => 'Mengapa progress belum penuh?',
            'answer' => 'Progress belum penuh jika masih ada siswa, TP/LM, atau nilai akhir yang belum lengkap. Buka mata pelajaran terkait dan lengkapi bagian yang masih kosong.',
            'keywords' => ['progress belum penuh', 'progress belum 100', 'nilai kosong', 'tp', 'lm', 'nilai akhir'],
        ],
        [
            'category' => 'Login dan Role',
            'question' => 'Mengapa selalu diarahkan ke halaman Ganti Password?',
            'answer' => 'Akun sedang memakai password sementara dari reset admin. Buat password baru terlebih dahulu. Setelah berhasil disimpan, dashboard pengajar atau wali bisa dibuka kembali.',
            'keywords' => ['selalu diarahkan', 'ganti password', 'wajib ganti', 'password sementara', 'dashboard'],
        ],
        [
            'category' => 'Login dan Role',
            'question' => 'Apakah pengajar dapat melihat password lama?',
            'answer' => 'Tidak. Password lama tidak dapat ditampilkan demi keamanan. Jika lupa password, minta admin melakukan reset dan gunakan password sementara untuk login.',
            'keywords' => ['password lama', 'lihat password', 'lupa password', 'reset password', 'keamanan'],
        ],
        [
            'category' => 'Tanda Tangan',
            'question' => 'Apakah pengajar dapat mengunggah tanda tangan sendiri?',
            'answer' => 'Belum. Pada fitur saat ini, tanda tangan guru dikelola oleh admin dari halaman Edit Pengajar. Hubungi admin jika tanda tangan perlu ditambahkan atau diganti.',
            'keywords' => ['upload tanda tangan', 'ttd', 'signature', 'pengajar upload', 'admin', 'wali kelas'],
        ],
        [
            'category' => 'Login dan Role',
            'question' => 'Mengapa role wali kelas tidak muncul?',
            'answer' => 'Role wali kelas muncul jika guru ditugaskan sebagai wali kelas pada tahun ajaran dan kelas yang sesuai. Jika seharusnya muncul, minta admin mengecek data pengajar.',
            'keywords' => ['role wali kelas', 'wali tidak muncul', 'ganti role', 'kelas wali', 'admin'],
        ],
        [
            'category' => 'Login dan Role',
            'question' => 'Bagaimana berpindah dari role pengajar ke wali kelas?',
            'answer' => 'Gunakan pilihan role pada profil. Pilih Wali Kelas jika tersedia. Jika tidak tersedia, berarti akun belum ditugaskan sebagai wali kelas pada konteks aktif.',
            'keywords' => ['berpindah role', 'pengajar ke wali', 'ganti role', 'wali kelas', 'profil'],
        ],
        [
            'category' => 'Troubleshooting',
            'question' => 'Kapan pengajar harus menghubungi admin?',
            'answer' => 'Hubungi admin jika mapel, siswa, role, TP/LM, atau akses tidak muncul meskipun semester aktif sudah benar. Sertakan nama mapel dan kelas agar mudah dicek.',
            'keywords' => ['hubungi admin', 'bantuan', 'akses ditolak', 'mapel tidak muncul', 'siswa tidak muncul'],
        ],
    ],

    'wali_kelas' => [
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Bagaimana mengubah capaian siswa?',
            'answer' => 'Buka Capaian Kompetensi, pilih mata pelajaran, lalu edit langsung teks capaian pada tabel siswa. Teks yang diubah menjadi khusus untuk siswa tersebut setelah disimpan.',
            'keywords' => ['capaian', 'ubah capaian', 'edit capaian', 'capaian tertinggi', 'capaian terendah', 'custom', 'kustom'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Apa arti Default dan Khusus?',
            'answer' => 'Default berarti deskripsi mengikuti pengaturan kalimat awal kelas. Khusus berarti deskripsi siswa sudah diubah sendiri dan tidak ikut berubah saat default kelas diganti.',
            'keywords' => ['default', 'khusus', 'custom', 'kustom', 'deskripsi khusus', 'kalimat awal'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Bagaimana mengembalikan capaian ke default?',
            'answer' => 'Gunakan tombol Gunakan default di dekat deskripsi siswa. Tindakan ini mengembalikan sisi yang dipilih saja, misalnya tertinggi saja atau terendah saja, lalu simpan semua perubahan.',
            'keywords' => ['gunakan default', 'reset default', 'kembali ke default', 'capaian default', 'tertinggi', 'terendah'],
        ],
        [
            'category' => 'Rapor',
            'question' => 'Mengapa rapor belum berubah?',
            'answer' => 'Setelah mengubah capaian, absensi, catatan, atau tanda tangan, simpan data lalu buat ulang atau unduh ulang rapor. File lama yang sudah dibuat tidak otomatis berubah.',
            'keywords' => ['rapor belum berubah', 'pdf belum berubah', 'docx', 'buat ulang', 'capaian berubah', 'download ulang'],
        ],
        [
            'category' => 'Tanda Tangan',
            'question' => 'Apakah tanda tangan muncul otomatis?',
            'answer' => 'Ya, pada DOCX/PDF tanda tangan wali kelas akan muncul jika admin sudah mengunggah tanda tangan untuk guru wali kelas tersebut dan template memakai placeholder yang benar.',
            'keywords' => ['tanda tangan otomatis', 'ttd', 'signature', 'wali kelas', 'docx', 'pdf', 'ttd_wali_kelas'],
        ],
        [
            'category' => 'Data Siswa',
            'question' => 'Bagaimana melihat daftar siswa?',
            'answer' => 'Buka menu Siswa pada halaman wali kelas. Daftar siswa mengikuti kelas wali, tahun ajaran, dan semester aktif. Jika kosong, cek role dan hubungi admin.',
            'keywords' => ['daftar siswa', 'lihat siswa', 'siswa wali', 'kelas wali', 'semester'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Bagaimana membuka Capaian Kompetensi?',
            'answer' => 'Masuk sebagai wali kelas, buka menu Capaian Kompetensi, lalu pilih mata pelajaran. Pastikan nilai mapel sudah tersedia agar deskripsi otomatis dapat terbentuk.',
            'keywords' => ['buka capaian', 'capaian kompetensi', 'mata pelajaran', 'nilai mapel', 'wali kelas'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Apa fungsi Pengaturan Kalimat Awal Capaian?',
            'answer' => 'Bagian ini mengatur pembuka deskripsi otomatis untuk siswa yang masih memakai Default. Pilih preset atau tulis kalimat sendiri, lalu simpan bersama perubahan lain.',
            'keywords' => ['pengaturan kalimat awal', 'kalimat awal', 'default capaian', 'preset', 'simpan semua'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Apa perbedaan capaian tertinggi dan terendah?',
            'answer' => 'Capaian tertinggi menggambarkan bagian yang paling dikuasai siswa. Capaian terendah menggambarkan bagian yang masih perlu dikembangkan atau mendapat perhatian.',
            'keywords' => ['capaian tertinggi', 'capaian terendah', 'tertinggi', 'terendah', 'nilai'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Apa arti deskripsi Default?',
            'answer' => 'Default berarti teks mengikuti kalimat awal kelas dan hasil otomatis dari nilai. Jika default kelas diganti, deskripsi siswa yang masih Default ikut berubah sebelum disimpan.',
            'keywords' => ['deskripsi default', 'default', 'kalimat awal', 'otomatis', 'capaian'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Apa arti deskripsi Khusus?',
            'answer' => 'Khusus berarti teks siswa sudah diedit langsung atau memakai pengaturan khusus. Teks ini tidak tertimpa ketika default kelas diganti.',
            'keywords' => ['deskripsi khusus', 'khusus', 'custom', 'kustom', 'tidak tertimpa default'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Bagaimana mengubah kalimat default untuk seluruh siswa?',
            'answer' => 'Ubah pilihan pada Pengaturan Kalimat Awal Capaian. Tabel akan menampilkan preview baru untuk siswa yang masih Default. Tekan Simpan Semua Perubahan untuk menyimpan.',
            'keywords' => ['ubah default', 'kalimat default', 'seluruh siswa', 'preview', 'simpan semua'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Mengapa perubahan default langsung terlihat di tabel?',
            'answer' => 'Tabel menampilkan preview agar wali kelas bisa mengecek hasil sebelum menyimpan. Perubahan itu belum tersimpan sampai tombol Simpan Semua Perubahan ditekan.',
            'keywords' => ['default langsung terlihat', 'preview', 'belum tersimpan', 'simpan semua', 'kalimat awal'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Apakah perubahan langsung tersimpan otomatis?',
            'answer' => 'Tidak. Perubahan pada default atau teks siswa tetap bersifat sementara sampai tombol Simpan Semua Perubahan ditekan. Jangan tinggalkan halaman jika masih ada tanda Belum disimpan.',
            'keywords' => ['otomatis tersimpan', 'belum disimpan', 'simpan semua', 'peringatan meninggalkan halaman'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Bagaimana mengubah deskripsi satu siswa?',
            'answer' => 'Edit langsung textarea capaian tertinggi atau terendah pada baris siswa. Hanya bagian yang diubah yang menjadi deskripsi khusus setelah disimpan.',
            'keywords' => ['ubah satu siswa', 'textarea', 'edit langsung', 'deskripsi khusus', 'capaian tertinggi', 'capaian terendah'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Apa fungsi tombol Gunakan default?',
            'answer' => 'Tombol ini menghapus pengaturan khusus pada sisi yang dipilih dan mengembalikan teks ke default kelas. Tertinggi dan terendah tidak saling berubah kecuali dipilih masing-masing.',
            'keywords' => ['gunakan default', 'fungsi gunakan default', 'reset', 'tertinggi', 'terendah'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Mengapa hanya ada satu tombol Simpan Semua Perubahan?',
            'answer' => 'Agar perubahan default dan perubahan per siswa tersimpan bersama. Jika ada kesalahan, sistem tidak menyimpan sebagian perubahan saja.',
            'keywords' => ['simpan semua', 'satu tombol simpan', 'perubahan capaian', 'default', 'siswa'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Apa arti Belum disimpan?',
            'answer' => 'Belum disimpan berarti ada perubahan di halaman yang masih sementara. Tekan Simpan Semua Perubahan agar data benar-benar tersimpan.',
            'keywords' => ['belum disimpan', 'dirty', 'perubahan sementara', 'simpan semua', 'capaian'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Mengapa muncul peringatan saat meninggalkan halaman?',
            'answer' => 'Peringatan muncul karena ada perubahan yang belum disimpan. Pilih tetap di halaman untuk menyimpan, atau lanjut pergi jika memang ingin membatalkan perubahan.',
            'keywords' => ['peringatan meninggalkan halaman', 'belum disimpan', 'keluar halaman', 'simpan semua'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Apakah mengubah capaian tertinggi ikut mengubah capaian terendah?',
            'answer' => 'Tidak. Capaian tertinggi dan terendah disimpan terpisah. Mengubah atau mengembalikan salah satu sisi tidak mengubah sisi lainnya.',
            'keywords' => ['tertinggi terendah', 'ubah tertinggi', 'ubah terendah', 'tidak ikut berubah', 'capaian'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Apakah deskripsi khusus tertimpa ketika default diubah?',
            'answer' => 'Tidak. Siswa yang sudah memakai deskripsi Khusus tetap mempertahankan teksnya. Default baru hanya memengaruhi siswa yang masih memakai Default.',
            'keywords' => ['khusus tertimpa', 'default diubah', 'deskripsi khusus', 'custom', 'kustom'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Mengapa perubahan capaian belum muncul di rapor?',
            'answer' => 'Pastikan perubahan sudah disimpan. Jika file rapor lama masih dipakai, buat ulang atau unduh ulang rapor agar capaian terbaru masuk ke dokumen.',
            'keywords' => ['capaian belum muncul', 'rapor', 'pdf belum berubah', 'buat ulang', 'simpan semua'],
        ],
        [
            'category' => 'Capaian Kompetensi',
            'question' => 'Apakah rapor perlu dibuat ulang setelah capaian diubah?',
            'answer' => 'Ya, untuk file DOCX/PDF yang sudah pernah dibuat. Setelah capaian disimpan, buka preview untuk mengecek lalu buat ulang atau unduh ulang rapor.',
            'keywords' => ['rapor perlu dibuat ulang', 'capaian diubah', 'docx', 'pdf', 'preview'],
        ],
        [
            'category' => 'Absensi dan Catatan',
            'question' => 'Bagaimana mengisi absensi?',
            'answer' => 'Buka menu Absensi, isi jumlah sakit, izin, dan tanpa keterangan untuk setiap siswa, lalu simpan. Data absensi tersimpan sesuai semester yang sedang dipilih.',
            'keywords' => ['absensi', 'sakit', 'izin', 'tanpa keterangan', 'semester', 'simpan'],
        ],
        [
            'category' => 'Absensi dan Catatan',
            'question' => 'Bagaimana mengisi catatan wali kelas?',
            'answer' => 'Buka menu Catatan Siswa, pilih atau isi catatan untuk siswa, lalu simpan. Gunakan bahasa singkat dan jelas sesuai kebutuhan rapor.',
            'keywords' => ['catatan wali kelas', 'catatan siswa', 'wali kelas', 'simpan catatan'],
        ],
        [
            'category' => 'Absensi dan Catatan',
            'question' => 'Bagaimana mengisi ekstrakurikuler dan prestasi?',
            'answer' => 'Buka menu ekstrakurikuler atau prestasi yang tersedia, pilih siswa, isi nilai atau deskripsi, lalu simpan. Pastikan data berada pada semester yang benar.',
            'keywords' => ['ekstrakurikuler', 'prestasi', 'nilai ekstra', 'deskripsi ekstra', 'semester'],
        ],
        [
            'category' => 'Data Siswa',
            'question' => 'Mengapa siswa wali kelas tidak muncul?',
            'answer' => 'Biasanya siswa belum terdaftar pada kelas wali untuk tahun ajaran dan semester aktif, atau role wali belum dipilih. Jika data seharusnya ada, hubungi admin.',
            'keywords' => ['siswa tidak muncul', 'kelas wali', 'role wali', 'tahun ajaran', 'semester', 'admin'],
        ],
        [
            'category' => 'Rapor',
            'question' => 'Bagaimana mengecek kelengkapan rapor?',
            'answer' => 'Cek nilai mapel, absensi, catatan, capaian, ekstrakurikuler, dan template rapor. Gunakan preview untuk melihat bagian yang masih belum sesuai.',
            'keywords' => ['kelengkapan rapor', 'cek rapor', 'nilai', 'absensi', 'catatan', 'capaian', 'template'],
        ],
        [
            'category' => 'Rapor',
            'question' => 'Bagaimana wali kelas membuka preview rapor?',
            'answer' => 'Buka menu Rapor, pilih siswa, lalu pilih preview. Preview menampilkan data terbaru yang sudah tersimpan untuk tahun ajaran dan semester tersebut.',
            'keywords' => ['preview rapor', 'rapor', 'lihat rapor', 'siswa', 'semester'],
        ],
        [
            'category' => 'Rapor',
            'question' => 'Mengapa rapor belum bisa dibuat?',
            'answer' => 'Biasanya template belum tersedia, data nilai belum lengkap, atau siswa tidak berada di kelas wali pada konteks yang dipilih. Cek dashboard dan hubungi admin jika perlu.',
            'keywords' => ['rapor belum bisa dibuat', 'template', 'nilai belum lengkap', 'kelas wali', 'dashboard'],
        ],
        [
            'category' => 'Rapor',
            'question' => 'Mengapa PDF rapor belum berubah setelah data diperbarui?',
            'answer' => 'PDF lama tidak otomatis berubah. Setelah data disimpan, buat ulang atau unduh ulang PDF agar file baru memakai nilai, capaian, catatan, atau tanda tangan terbaru.',
            'keywords' => ['pdf belum berubah', 'pdf', 'docx', 'buat ulang', 'download ulang', 'data diperbarui'],
        ],
        [
            'category' => 'Rapor',
            'question' => 'Apa yang harus dilakukan setelah mengubah capaian?',
            'answer' => 'Tekan Simpan Semua Perubahan, cek preview rapor, lalu buat ulang atau unduh ulang DOCX/PDF jika dokumen sebelumnya sudah pernah dibuat.',
            'keywords' => ['setelah mengubah capaian', 'simpan semua', 'preview', 'docx', 'pdf', 'buat ulang'],
        ],
        [
            'category' => 'Tanda Tangan',
            'question' => 'Apa yang terjadi jika admin belum mengunggah tanda tangan?',
            'answer' => 'Rapor tetap bisa dibuat. Pada DOCX/PDF, area tanda tangan wali kelas akan kosong sampai admin mengunggah gambar tanda tangan.',
            'keywords' => ['admin belum upload tanda tangan', 'ttd belum ada', 'area kosong', 'docx', 'pdf'],
        ],
        [
            'category' => 'Tanda Tangan',
            'question' => 'Apakah wali perlu mengunggah tanda tangan sendiri?',
            'answer' => 'Tidak. Pada fitur saat ini, tanda tangan guru dikelola oleh admin. Jika tanda tangan belum ada atau perlu diganti, hubungi admin.',
            'keywords' => ['wali upload tanda tangan', 'unggah ttd sendiri', 'admin', 'tanda tangan', 'signature'],
        ],
        [
            'category' => 'Login dan Role',
            'question' => 'Bagaimana wali kelas mengganti password setelah admin mereset?',
            'answer' => 'Login memakai password sementara, lalu isi password baru pada halaman Ganti Password. Setelah berhasil, akses wali kelas atau pengajar akan terbuka kembali.',
            'keywords' => ['ganti password', 'reset password', 'password sementara', 'wajib ganti', 'login'],
        ],
        [
            'category' => 'Login dan Role',
            'question' => 'Mengapa tidak dapat membuka dashboard sebelum mengganti password?',
            'answer' => 'Akun masih memakai password sementara dari admin. Ganti password terlebih dahulu agar akun aman, lalu buka kembali dashboard.',
            'keywords' => ['tidak dapat membuka dashboard', 'ganti password', 'password sementara', 'wajib ganti'],
        ],
        [
            'category' => 'Login dan Role',
            'question' => 'Bagaimana berpindah ke role pengajar?',
            'answer' => 'Gunakan pilihan role pada profil jika guru juga memiliki tugas pengajar. Pilih Pengajar untuk membuka menu input nilai.',
            'keywords' => ['berpindah role', 'role pengajar', 'ganti role', 'input nilai', 'profil'],
        ],
        [
            'category' => 'Login dan Role',
            'question' => 'Mengapa role wali kelas tidak tersedia?',
            'answer' => 'Role wali kelas tersedia jika guru ditugaskan sebagai wali kelas pada tahun ajaran dan kelas yang sesuai. Hubungi admin jika tugas wali belum muncul.',
            'keywords' => ['role wali tidak tersedia', 'wali kelas tidak muncul', 'kelas wali', 'tahun ajaran', 'admin'],
        ],
        [
            'category' => 'Troubleshooting',
            'question' => 'Kapan wali kelas harus menghubungi admin?',
            'answer' => 'Hubungi admin jika siswa, role, template, tanda tangan, atau akses rapor tidak muncul meskipun tahun ajaran dan semester sudah benar.',
            'keywords' => ['hubungi admin', 'bantuan', 'siswa tidak muncul', 'template', 'tanda tangan', 'akses rapor'],
        ],
    ],
];
