<?php

return [
    'roles' => [
        'admin' => [
            'Mulai Cepat',
            'Masuk & Akun',
            'Administrasi Data',
            'Tahun Ajaran',
            'Pembelajaran',
            'Nilai',
            'Kelas Wali',
            'Rapor',
            'Download & Cetak',
            'Template Rapor',
            'Email & Pemulihan',
            'Masalah Umum',
            'Keamanan Akun',
        ],
        'pengajar' => [
            'Mulai Cepat',
            'Masuk & Akun',
            'Pembelajaran',
            'Nilai',
            'Rapor',
            'Email & Pemulihan',
            'Masalah Umum',
            'Keamanan Akun',
        ],
        'wali_kelas' => [
            'Mulai Cepat',
            'Masuk & Akun',
            'Kelas Wali',
            'Nilai',
            'Rapor',
            'Download & Cetak',
            'Template Rapor',
            'Email & Pemulihan',
            'Masalah Umum',
            'Keamanan Akun',
        ],
    ],

    'topics' => [
        [
            'category' => 'Mulai Cepat',
            'roles' => ['admin'],
            'question' => 'Mulai cepat untuk Admin',
            'answer' => "Siapkan aplikasi dengan urutan yang mudah diperiksa.\n\n1. Lengkapi Profile Sekolah.\n2. Buat dan aktifkan Tahun Ajaran yang digunakan.\n3. Buat Kelas, lalu tambahkan Pengajar dan penugasannya.\n4. Tambahkan Siswa secara manual atau melalui file Excel.\n5. Buat Mata Pelajaran, Lingkup Materi, dan Tujuan Pembelajaran.\n6. Periksa KKM dan Bobot Nilai.\n7. Upload dan aktifkan template UTS serta UAS di Format Rapor.\n8. Pilih jenis rapor yang dibuka untuk Wali Kelas.\n\nMenu akademik tetap terkunci bila Profile Sekolah atau Tahun Ajaran aktif belum tersedia.",
            'keywords' => ['mulai admin', 'setup awal', 'urutan data', 'profil sekolah', 'tahun ajaran', 'format rapor'],
        ],
        [
            'category' => 'Mulai Cepat',
            'roles' => ['pengajar'],
            'question' => 'Mulai cepat untuk Pengajar',
            'answer' => "Setelah masuk, pilih peran Pengajar bila akun memiliki lebih dari satu peran. Buka Data Mata Pelajaran untuk memeriksa kelas, mapel, Lingkup Materi, dan Tujuan Pembelajaran yang menjadi tanggung jawab Anda.\n\nSetelah struktur pembelajaran lengkap, buka Data Nilai Pelajaran. Nilai dapat diisi langsung atau dimuat dari template Excel. Periksa kembali hasilnya lalu klik Simpan. Status Lengkap atau Belum Lengkap ditampilkan per siswa.",
            'keywords' => ['mulai pengajar', 'dashboard pengajar', 'data mata pelajaran', 'input nilai', 'lm tp'],
        ],
        [
            'category' => 'Mulai Cepat',
            'roles' => ['wali_kelas'],
            'question' => 'Mulai cepat untuk Wali Kelas',
            'answer' => "Setelah masuk, pilih peran Wali Kelas bila akun juga menjadi Pengajar. Dashboard dan menu Wali Kelas hanya menampilkan kelas yang menjadi tanggung jawab Anda pada konteks tahun ajaran aktif.\n\nPeriksa Siswa, Capaian Kompetensi, Ekstrakurikuler, Absensi, dan Rapor. Pada halaman Rapor, lihat status nilai dan kehadiran sebelum mencetak atau mengunduh dokumen.",
            'keywords' => ['mulai wali kelas', 'dashboard wali', 'kelas tanggung jawab', 'absensi', 'rapor'],
        ],
        [
            'category' => 'Mulai Cepat',
            'roles' => ['admin', 'pengajar', 'wali_kelas'],
            'question' => 'Membuka menu di desktop dan ponsel',
            'answer' => "Di desktop, gunakan menu samping untuk berpindah halaman. Di layar yang lebih kecil, buka tombol menu untuk menampilkan pilihan yang sama.\n\nTombol Pusat Bantuan berbentuk ikon bulat di kanan bawah. Klik ikon tersebut untuk mencari jawaban singkat atau membuka Pusat Bantuan lengkap. Tombol ini tidak mengubah data.",
            'keywords' => ['menu desktop', 'menu ponsel', 'mobile', 'sidebar', 'pusat bantuan', 'ikon bantuan'],
        ],

        [
            'category' => 'Masuk & Akun',
            'roles' => ['admin', 'pengajar', 'wali_kelas'],
            'question' => 'Masuk dengan Username atau Email',
            'answer' => "Admin, Pengajar, dan Wali Kelas memakai halaman Masuk yang sama. Isi kolom Username atau Email, lalu masukkan password. Sistem menentukan akun yang sesuai tanpa pilihan peran di layar.\n\nJika username atau email yang sama tercatat pada lebih dari satu akun, proses masuk ditolak agar tidak membuka akun yang salah. Hubungi Admin untuk memperbaiki data akun. Pesan gagal masuk sengaja dibuat umum dan tidak menunjukkan jenis akun.",
            'keywords' => ['login', 'masuk', 'username', 'email', 'password', 'sandi', 'akun tidak ditemukan'],
        ],
        [
            'category' => 'Masuk & Akun',
            'roles' => ['pengajar', 'wali_kelas'],
            'question' => 'Memilih dan mengganti peran Guru',
            'answer' => "Akun Guru dapat memiliki peran Pengajar, Wali Kelas, atau keduanya. Jika tersedia lebih dari satu peran, gunakan pilihan peran pada menu akun.\n\nPilih Pengajar untuk mengelola pembelajaran dan nilai. Pilih Wali Kelas untuk mengelola kelas wali, absensi, capaian kompetensi, dan rapor. Akses tetap dibatasi oleh penugasan pada tahun ajaran aktif.",
            'keywords' => ['ganti role', 'ganti peran', 'pengajar', 'wali kelas', 'menu tidak muncul', 'akses ditolak'],
        ],
        [
            'category' => 'Masuk & Akun',
            'roles' => ['pengajar', 'wali_kelas'],
            'question' => 'Profil Guru dan status email',
            'answer' => "Halaman Profil menampilkan data akun Guru. Email bersifat opsional, tetapi harus berstatus Terverifikasi agar dapat dipakai untuk pemulihan password mandiri.\n\nJika email tersedia namun belum terverifikasi, aplikasi menampilkan pengingat. Klik Verifikasi Email untuk meminta tautan, lalu buka email tersebut saat masuk dengan akun Guru yang terkait. Perubahan alamat email membuat status verifikasi kembali kosong.",
            'keywords' => ['profil guru', 'email guru', 'belum diverifikasi', 'terverifikasi', 'verifikasi email'],
        ],
        [
            'category' => 'Masuk & Akun',
            'roles' => ['admin'],
            'question' => 'Mengubah password Admin',
            'answer' => "Buka menu akun lalu pilih Ubah Password. Masukkan password saat ini, password baru minimal 8 karakter, dan konfirmasinya. Setelah berhasil, gunakan password baru untuk masuk berikutnya.\n\nAplikasi hanya memiliki satu akun Admin. Fitur ini mengubah akun yang sama dan tidak membuat Admin baru.",
            'keywords' => ['ubah password admin', 'ganti sandi admin', 'password saat ini', 'akun admin'],
        ],
        [
            'category' => 'Masuk & Akun',
            'roles' => ['pengajar', 'wali_kelas'],
            'question' => 'Password sementara dari Admin',
            'answer' => "Jika Guru tidak dapat memulihkan password melalui email, Admin dapat menetapkan password sementara dari Data Pengajar. Saat Guru masuk dengan password tersebut, aplikasi mewajibkan pembuatan password baru sebelum halaman lain dapat digunakan.\n\nMasukkan password baru dan konfirmasinya. Setelah berhasil, akses kembali ke dashboard sesuai peran yang dipilih.",
            'keywords' => ['password sementara', 'reset oleh admin', 'wajib ganti password', 'must change password', 'tidak bisa masuk'],
        ],
        [
            'category' => 'Masuk & Akun',
            'roles' => ['admin', 'pengajar', 'wali_kelas'],
            'question' => 'Keluar dan sesi yang berakhir',
            'answer' => "Gunakan tombol Keluar setelah selesai, terutama pada komputer bersama. Bila sesi berakhir karena tidak aktif atau halaman sudah lama terbuka, Anda akan diminta masuk kembali.\n\nJika formulir menampilkan halaman kedaluwarsa, buka ulang halaman dari menu, periksa data yang belum tersimpan, lalu kirim kembali setelah masuk.",
            'keywords' => ['logout', 'keluar', 'sesi habis', 'session timeout', 'halaman kedaluwarsa', '419'],
        ],
        [
            'category' => 'Masuk & Akun',
            'roles' => ['admin'],
            'question' => 'Tentang setup Admin pertama',
            'answer' => "Setup Admin pertama hanya tersedia pada pemasangan baru ketika belum ada akun Admin dan pengelola sistem sudah menyiapkan kode setup. Setelah satu Admin berhasil dibuat, halaman setup tidak dapat digunakan lagi.\n\nSetup awal bukan cara memulihkan password. Gunakan Lupa password? atau Ubah Password untuk akun Admin yang sudah ada. Kode setup tidak boleh dibagikan atau dicantumkan di Pusat Bantuan.",
            'keywords' => ['admin pertama', 'initial admin setup', 'setup awal admin', 'satu admin', 'lupa password admin'],
        ],

        [
            'category' => 'Administrasi Data',
            'roles' => ['admin'],
            'question' => 'Dashboard dan prasyarat data Admin',
            'answer' => "Dashboard merangkum kondisi data sekolah, kelas, siswa, dan pekerjaan akademik. Jika Profile Sekolah atau Tahun Ajaran aktif belum tersedia, aplikasi menampilkan peringatan dan menonaktifkan menu yang bergantung pada keduanya.\n\nLengkapi prasyarat dari tautan yang ditampilkan. Jangan membuat data akademik pada konteks tahun yang salah hanya untuk menghilangkan peringatan.",
            'keywords' => ['dashboard admin', 'menu terkunci', 'prasyarat', 'profil belum lengkap', 'tahun ajaran belum aktif'],
        ],
        [
            'category' => 'Administrasi Data',
            'roles' => ['admin'],
            'question' => 'Profile Sekolah dan data resmi rapor',
            'answer' => "Buka Profile Sekolah untuk mengisi identitas sekolah, alamat, NPSN, kontak, kepala sekolah, dan data lain yang tersedia. Informasi ini dipakai pada halaman dan dokumen rapor.\n\nPeriksa kembali sebelum menyiapkan rapor. Setelah data resmi berubah, buat ulang dokumen yang perlu memuat informasi terbaru.",
            'keywords' => ['profile sekolah', 'profil sekolah', 'npsn', 'kepala sekolah', 'alamat', 'logo', 'data rapor'],
        ],
        [
            'category' => 'Administrasi Data',
            'roles' => ['admin'],
            'question' => 'Mengelola Kelas dan kelas paralel',
            'answer' => "Setiap rombongan belajar dibuat sebagai data Kelas tersendiri pada tahun ajaran yang dipilih. Isi nomor tingkat dan nama kelas dengan konsisten, misalnya tingkat 4 dengan nama A atau nama rombel yang digunakan sekolah.\n\nPenugasan Wali Kelas, siswa, dan mata pelajaran bergantung pada kelas ini. Jika kelas sudah dipakai, baca konfirmasi dan pemeriksaan keterkaitan sebelum mengubah atau menghapusnya.",
            'keywords' => ['kelas', 'kelas paralel', 'rombel', 'nomor kelas', 'nama kelas', 'wali kelas'],
        ],
        [
            'category' => 'Administrasi Data',
            'roles' => ['admin'],
            'question' => 'Mengelola Pengajar, peran, dan penugasan',
            'answer' => "Di menu Pengajar, Admin dapat menambah atau mengubah data Guru, akun login, kelas mengajar, dan penugasan Wali Kelas. Satu Guru dapat menjalankan peran Pengajar dan Wali Kelas bila penugasannya tersedia.\n\nEmail boleh dikosongkan. Email baru atau email yang berubah selalu berstatus Belum diverifikasi sampai Guru membuka tautan verifikasi. Perubahan penugasan memengaruhi menu dan data yang dapat diakses Guru.",
            'keywords' => ['data pengajar', 'guru', 'penugasan', 'wali kelas', 'kelas mengajar', 'peran guru', 'email opsional'],
        ],
        [
            'category' => 'Administrasi Data',
            'roles' => ['admin'],
            'question' => 'Status email dan tindakan akun Pengajar',
            'answer' => "Kolom Email menampilkan Belum diverifikasi berwarna kuning atau Terverifikasi berwarna hijau. Klik Belum diverifikasi, baca konfirmasi alamat tujuan, lalu pilih Kirim Verifikasi bila alamat sudah benar. Menyimpan data Pengajar tidak otomatis mengirim email.\n\nJika Guru lupa password dan tidak dapat memakai email terverifikasi, gunakan Reset Password pada detail Pengajar. Password sementara membuat Guru wajib mengganti password saat masuk berikutnya.",
            'keywords' => ['belum diverifikasi', 'terverifikasi', 'kirim verifikasi', 'reset password guru', 'password sementara'],
        ],
        [
            'category' => 'Administrasi Data',
            'roles' => ['admin'],
            'question' => 'Menambah dan memperbarui Siswa',
            'answer' => "Admin dapat menambah siswa secara manual dari menu Siswa. Isi identitas dan pilih kelas pada tahun ajaran yang benar. NIS dan NISN harus mengikuti aturan keunikan yang ditampilkan aplikasi.\n\nSaat mengedit siswa, periksa kembali kelas dan identitasnya. Perpindahan konteks akademik dilakukan melalui alur tahun ajaran atau kenaikan kelas, bukan dengan memilih kelas lama secara sembarang.",
            'keywords' => ['tambah siswa', 'edit siswa', 'nis', 'nisn', 'kelas siswa', 'data siswa'],
        ],
        [
            'category' => 'Administrasi Data',
            'roles' => ['admin'],
            'question' => 'Import Siswa dari Excel',
            'answer' => "Unduh template siswa dari aplikasi, isi tanpa mengubah judul atau susunan kolom, lalu upload melalui halaman Upload Data Siswa. Gunakan format nilai dan tanggal yang diminta pada template.\n\nJika import ditolak, baca pesan pada baris yang bermasalah. Perbaiki data duplikat, kelas yang tidak cocok, kolom wajib, atau format tanggal, lalu upload ulang. Data yang tidak lolos pemeriksaan tidak boleh dianggap sudah masuk.",
            'keywords' => ['import siswa', 'upload siswa', 'excel siswa', 'template siswa', 'baris error', 'tanggal lahir'],
        ],
        [
            'category' => 'Administrasi Data',
            'roles' => ['admin'],
            'question' => 'Ekstrakurikuler dan Prestasi',
            'answer' => "Menu Ekstrakurikuler mengelola pilihan kegiatan dan pembinanya. Menu Prestasi mencatat prestasi siswa berdasarkan kelas, siswa, jenis prestasi, dan informasi yang tersedia pada formulir.\n\nData Wali Kelas tentang keikutsertaan atau nilai ekstrakurikuler berbeda dari daftar kegiatan yang disiapkan Admin. Periksa siswa dan periode sebelum menyimpan karena data ini dapat muncul pada rapor.",
            'keywords' => ['ekstrakurikuler', 'prestasi', 'pembina', 'kegiatan', 'siswa berprestasi', 'rapor'],
        ],
        [
            'category' => 'Administrasi Data',
            'roles' => ['admin'],
            'question' => 'Recycle Bin, pulihkan, dan hapus permanen',
            'answer' => "Penghapusan biasa pada data yang mendukung Recycle Bin memindahkan data ke tempat pemulihan. Gunakan Pulihkan bila data masih diperlukan. Beberapa data anak baru dapat dipulihkan setelah data induknya dipulihkan lebih dulu.\n\nHapus Permanen tidak dapat dibatalkan dan dapat ditolak bila data masih terhubung dengan alur akademik. Baca pemeriksaan keterkaitan dan konfirmasi satu per satu; jangan memakai hapus permanen sebagai cara merapikan data yang masih aktif.",
            'keywords' => ['recycle bin', 'sampah', 'pulihkan', 'restore', 'hapus permanen', 'data terkait', 'arsip'],
        ],
        [
            'category' => 'Administrasi Data',
            'roles' => ['admin'],
            'question' => 'Riwayat aktivitas dan notifikasi Admin',
            'answer' => "Riwayat aktivitas membantu Admin meninjau tindakan yang tercatat dan, bila tersedia, mengekspor daftar sesuai tampilan. Panel Informasi menampilkan pemberitahuan aplikasi dan jumlah yang belum dibaca.\n\nMenandai atau menghapus notifikasi hanya mengubah pemberitahuan milik akun; tindakan itu tidak menghapus nilai, siswa, atau data akademik asalnya.",
            'keywords' => ['audit', 'riwayat aktivitas', 'export', 'notifikasi admin', 'informasi', 'belum dibaca'],
        ],
        [
            'category' => 'Administrasi Data',
            'roles' => ['admin'],
            'question' => 'Pencarian, filter, dan data yang tampak hilang',
            'answer' => "Daftar data dapat dipengaruhi oleh pencarian, filter, urutan, halaman, dan tahun ajaran yang sedang dipilih. Jika data tidak terlihat, kosongkan kata pencarian, reset filter, periksa halaman berikutnya, lalu cek pilihan tahun ajaran dan semester di bagian atas.\n\nJangan membuat data duplikat sebelum memastikan data lama tidak tersembunyi oleh filter atau berada di arsip.",
            'keywords' => ['search', 'pencarian', 'filter', 'pagination', 'data hilang', 'reset filter', 'arsip'],
        ],

        [
            'category' => 'Tahun Ajaran',
            'roles' => ['admin'],
            'question' => 'Tahun Ajaran aktif, semester, dan tampilan data',
            'answer' => "Tahun Ajaran dan semester aktif menentukan konteks kelas, penugasan, siswa, mata pelajaran, nilai, dan rapor yang sedang dikerjakan. Pemilih Tahun Ajaran di bagian atas dapat dipakai untuk melihat konteks yang tersedia, tetapi status aktif tetap menentukan pekerjaan berjalan.\n\nGanjil dan Genap adalah semester. UTS dan UAS adalah jenis rapor di dalam semester aktif; keduanya bukan pengganti semester.",
            'keywords' => ['tahun ajaran aktif', 'semester aktif', 'ganjil', 'genap', 'pilih tahun ajaran', 'uts uas'],
        ],
        [
            'category' => 'Tahun Ajaran',
            'roles' => ['admin'],
            'question' => 'Melanjutkan Semester Ganjil ke Genap',
            'answer' => "Alur Lanjutkan ke Semester Genap hanya dapat dijalankan dari Semester Ganjil yang aktif. Tinjau ringkasan kesiapan, baca data yang akan dibawa, lalu ketik kalimat konfirmasi yang diminta.\n\nStruktur akademik yang disiapkan aplikasi dapat disalin ke Semester Genap, tetapi nilai, catatan, rapor, dan hasil pekerjaan siswa Semester Ganjil tidak menjadi pekerjaan Semester Genap. Data Semester Ganjil tetap tersimpan. Jika Semester Genap sudah ada atau berada di arsip, gunakan data tersebut dan jangan membuat ulang.",
            'keywords' => ['lanjut semester genap', 'transisi semester', 'ganjil ke genap', 'salin struktur', 'nilai tidak disalin'],
        ],
        [
            'category' => 'Tahun Ajaran',
            'roles' => ['admin'],
            'question' => 'Membuat Tahun Ajaran berikutnya',
            'answer' => "Tahun ajaran berikutnya dibuat dari sumber Semester Genap. Gunakan alur Buat Tahun Ajaran Berikutnya agar struktur yang didukung aplikasi dapat disiapkan dengan konteks baru. Baca ringkasan dan ketik konfirmasi yang diminta.\n\nSiswa tidak dibuat sebagai data baru. Penempatan siswa pada tahun ajaran tujuan dilakukan melalui Kenaikan Kelas. Periksa kelas, penugasan Guru, mata pelajaran, dan template sebelum tahun baru dipakai.",
            'keywords' => ['tahun ajaran berikutnya', 'copy tahun ajaran', 'semester genap', 'struktur baru', 'kenaikan kelas'],
        ],
        [
            'category' => 'Tahun Ajaran',
            'roles' => ['admin'],
            'question' => 'Kenaikan kelas dan siswa tinggal kelas',
            'answer' => "Kenaikan kelas diproses setelah Semester Genap dan membutuhkan tahun ajaran tujuan Semester Ganjil serta kelas tujuan yang sesuai. Buka Kenaikan Kelas, pilih kelas sumber, tinjau siswa dan kelas tujuan, lalu gunakan tindakan untuk siswa yang dipilih sesuai layar.\n\nGunakan pilihan Tinggal Kelas bila siswa tetap pada tingkat yang sama. Jangan menjalankan proses sebelum nilai dan rapor selesai. Jika aplikasi menampilkan mode perencanaan atau tombol dinonaktifkan, ikuti batasan tersebut dan jangan menganggap siswa sudah dipindahkan.",
            'keywords' => ['kenaikan kelas', 'tinggal kelas', 'siswa terpilih', 'kelas tujuan', 'semester genap', 'mode perencanaan'],
        ],
        [
            'category' => 'Tahun Ajaran',
            'roles' => ['admin'],
            'question' => 'Mengarsipkan atau memulihkan Tahun Ajaran',
            'answer' => "Tahun Ajaran lama dapat ditampilkan bersama arsip. Pulihkan lebih dulu bila periode yang berada di arsip perlu digunakan kembali. Penghapusan permanen dapat ditolak jika periode masih terhubung dengan kelas, siswa, nilai, template, atau alur akademik lain.\n\nSebelum mengarsipkan atau mengaktifkan periode, pastikan hanya konteks yang benar yang menjadi aktif dan tidak ada pekerjaan pengguna yang masih berlangsung.",
            'keywords' => ['arsip tahun ajaran', 'tampilkan arsip', 'pulihkan tahun ajaran', 'aktifkan tahun ajaran', 'hapus permanen'],
        ],

        [
            'category' => 'Pembelajaran',
            'roles' => ['admin'],
            'question' => 'Mata Pelajaran, jenis pengajaran, dan Pengajar',
            'answer' => "Buat Mata Pelajaran pada kelas, tahun ajaran, dan semester yang benar. Pilih jenis pengajaran serta Guru yang bertanggung jawab sesuai pilihan pada formulir. Untuk kelas yang menggunakan Wali Kelas sebagai pengajar, pastikan penugasan Wali Kelas sudah tersedia.\n\nNama mapel yang sama pada kelas paralel tetap merupakan pembelajaran terpisah. Perubahan kelas atau Pengajar memengaruhi siapa yang dapat membuka nilai dan struktur pembelajaran.",
            'keywords' => ['mata pelajaran', 'pelajaran', 'jenis pengajaran', 'guru pengajar', 'kelas paralel', 'muatan lokal'],
        ],
        [
            'category' => 'Pembelajaran',
            'roles' => ['admin'],
            'question' => 'Lingkup Materi dan Tujuan Pembelajaran untuk Admin',
            'answer' => "Lingkup Materi mengelompokkan materi pada sebuah Mata Pelajaran. Tujuan Pembelajaran berada di dalam Lingkup Materi. Setiap Lingkup Materi perlu memiliki Tujuan Pembelajaran agar pembelajaran siap dipakai untuk template dan input nilai.\n\nSaat menghapus LM atau TP, aplikasi memeriksa data yang bergantung padanya. Jika penghapusan ditolak, selesaikan atau tinjau keterkaitan yang ditampilkan; jangan mengubah struktur ketika Pengajar sedang mengisi nilai.",
            'keywords' => ['lingkup materi', 'lm', 'tujuan pembelajaran', 'tp', 'ketergantungan', 'hapus tp'],
        ],
        [
            'category' => 'Pembelajaran',
            'roles' => ['pengajar'],
            'question' => 'Data Mata Pelajaran yang dapat dibuka Pengajar',
            'answer' => "Data Mata Pelajaran hanya menampilkan pembelajaran yang ditugaskan kepada akun Pengajar pada tahun ajaran dan semester aktif. Dari halaman ini, Pengajar dapat mengelola Lingkup Materi dan Tujuan Pembelajaran sesuai kewenangannya.\n\nJika kelas atau mapel tidak muncul, periksa peran yang dipilih dan konteks tahun ajaran. Hubungi Admin bila penugasannya belum benar.",
            'keywords' => ['data mata pelajaran', 'mapel tidak muncul', 'kelas diajar', 'penugasan pengajar', 'semester aktif'],
        ],
        [
            'category' => 'Pembelajaran',
            'roles' => ['pengajar'],
            'question' => 'Melengkapi Lingkup Materi dan Tujuan Pembelajaran',
            'answer' => "Buka Data Mata Pelajaran, lalu tambah atau edit Lingkup Materi dan Tujuan Pembelajaran. Setiap Lingkup Materi harus memiliki setidaknya satu Tujuan Pembelajaran agar status pembelajaran siap.\n\nBila tersedia mapel yang sesuai di kelas paralel, gunakan pilihan salin LM/TP untuk mengurangi pengetikan ulang. Periksa hasil salinan sebelum dipakai untuk nilai.",
            'keywords' => ['lengkapi lm tp', 'status siap', 'salin lm tp', 'kelas paralel', 'tujuan pembelajaran belum lengkap'],
        ],
        [
            'category' => 'Pembelajaran',
            'roles' => ['pengajar'],
            'question' => 'Mengubah atau menghapus LM/TP yang sudah dipakai',
            'answer' => "Aplikasi melakukan pemeriksaan sebelum LM atau TP yang terhubung dengan data lain dihapus. Jika tombol menampilkan peringatan, baca daftar keterkaitan terlebih dahulu.\n\nPerubahan struktur dapat memengaruhi kolom input, file Excel, dan nilai yang berkaitan. Selesaikan perubahan struktur sebelum membagikan template nilai, dan unduh template baru setelah struktur berubah.",
            'keywords' => ['hapus lm', 'hapus tp', 'dependency check', 'struktur berubah', 'template nilai lama'],
        ],

        [
            'category' => 'Nilai',
            'roles' => ['admin'],
            'question' => 'KKM dan Bobot Nilai',
            'answer' => "Admin mengatur KKM dan Bobot Nilai pada konteks tahun ajaran yang dipilih. KKM dapat diatur per Mata Pelajaran atau melalui tindakan bersama yang tersedia. Bobot yang tampil untuk Pengajar digunakan dalam perhitungan Nilai Akhir Rapor.\n\nPerubahan pengaturan dapat mengubah hasil perhitungan saat nilai disimpan atau dokumen dibuat ulang. Pastikan keputusan sekolah sudah benar sebelum masa pengisian nilai.",
            'keywords' => ['kkm', 'bobot nilai', 'bobot tp', 'bobot lm', 'bobot as', 'nilai akhir rapor'],
        ],
        [
            'category' => 'Nilai',
            'roles' => ['pengajar'],
            'question' => 'Input Nilai manual dan cara menyimpan',
            'answer' => "Buka Data Nilai Pelajaran lalu pilih Input Nilai pada kelas dan mapel yang ditugaskan. Isi nilai TP, LM, Nilai Tes, dan Nilai Non-Tes pada kolom yang tersedia. Nilai turunan dan Nilai Akhir Rapor dihitung oleh aplikasi.\n\nNilai harus berada pada rentang 0 sampai 100. Klik Simpan setelah memeriksa seluruh siswa. Berpindah halaman sebelum menyimpan dapat membuat perubahan hilang.",
            'keywords' => ['input nilai manual', 'nilai tp', 'nilai lm', 'nilai tes', 'nilai non tes', 'simpan nilai', '0 sampai 100'],
        ],
        [
            'category' => 'Nilai',
            'roles' => ['pengajar', 'wali_kelas'],
            'question' => 'Arti nilai kosong dan nilai 0',
            'answer' => "Kolom kosong berarti nilai belum diisi. Angka 0 adalah nilai nyata dan tetap disimpan serta dihitung. Jangan mengisi 0 hanya untuk menutup kolom yang belum dinilai.\n\nPerbedaan ini juga berlaku saat import Excel dan saat aplikasi menilai kesiapan rapor.",
            'keywords' => ['nilai kosong', 'nilai nol', 'nilai 0', 'blank', 'null', 'excel kosong'],
        ],
        [
            'category' => 'Nilai',
            'roles' => ['pengajar'],
            'question' => 'Arti status Lengkap dan Belum Lengkap',
            'answer' => "Lengkap berarti siswa memiliki masukan yang diperlukan pada TP, LM, Nilai Tes, dan Nilai Non-Tes untuk pembelajaran tersebut. Belum Lengkap berarti masih ada bagian yang belum terisi. Penghitung di atas tabel menunjukkan jumlah siswa lengkap.\n\nStatus diperbarui saat Anda mengisi form dan disimpan bersama nilai. Periksa siswa berstatus Belum Lengkap sebelum meninggalkan halaman.",
            'keywords' => ['status lengkap', 'belum lengkap', 'siswa lengkap', 'status nilai', 'finalisasi nilai'],
        ],
        [
            'category' => 'Nilai',
            'roles' => ['pengajar'],
            'question' => 'Mengedit atau menghapus nilai yang pernah disimpan',
            'answer' => "Buka kembali Input Nilai pada kelas dan Mata Pelajaran yang sama, ubah kolom yang diperlukan, lalu klik Simpan. Dokumen rapor yang dibuat setelah perubahan akan memakai data terbaru.\n\nTombol hapus pada baris siswa menghapus nilai pembelajaran siswa tersebut setelah konfirmasi. Gunakan hanya bila memang perlu mengosongkan data; untuk koreksi biasa, lebih aman mengedit lalu menyimpan.",
            'keywords' => ['edit nilai', 'ubah nilai', 'hapus nilai', 'koreksi nilai', 'nilai terbaru', 'simpan ulang'],
        ],
        [
            'category' => 'Nilai',
            'roles' => ['pengajar'],
            'question' => 'Download template nilai Excel',
            'answer' => "Gunakan Download Template Nilai untuk satu pembelajaran. Download Semua Template Siap membuat satu workbook berisi pembelajaran yang siap, tetapi hanya tersedia bila semua pembelajaran yang akan disertakan sudah memiliki LM/TP lengkap.\n\nGunakan file terbaru dari aplikasi. Jangan mengubah judul kolom, identitas kelas/mapel, nama sheet, atau kolom tersembunyi.",
            'keywords' => ['download template nilai', 'excel nilai', 'semua template siap', 'workbook', 'lm tp lengkap'],
        ],
        [
            'category' => 'Nilai',
            'roles' => ['pengajar'],
            'question' => 'Import satu file nilai Excel',
            'answer' => "Pada halaman Input Nilai, klik Import Nilai Excel lalu pilih template yang sesuai. Aplikasi membaca file ke layar preview/form terlebih dahulu; nilai belum tersimpan pada tahap ini.\n\nPeriksa ringkasan baris valid dan pesan kesalahan. Jika valid, cek kembali nilai yang dimuat lalu klik Simpan. File dari kelas, mapel, atau struktur LM/TP yang berbeda akan ditolak.",
            'keywords' => ['import nilai excel', 'upload nilai', 'preview excel', 'baris valid', 'nilai belum disimpan'],
        ],
        [
            'category' => 'Nilai',
            'roles' => ['pengajar'],
            'question' => 'Upload Semua Nilai Excel per sheet',
            'answer' => "Upload workbook yang berasal dari Download Semua Template Siap. Aplikasi menampilkan preview setiap sheet secara berurutan. Periksa sheet saat ini, lalu klik Simpan & Lanjut.\n\nSheet yang belum disimpan belum masuk ke data nilai. Preview dapat kedaluwarsa; bila itu terjadi, upload ulang workbook terbaru dan lanjutkan dari awal. Jangan membuka sheet berikutnya dengan melewati sheet yang belum disimpan.",
            'keywords' => ['upload semua nilai', 'multi sheet', 'simpan dan lanjut', 'preview kedaluwarsa', 'workbook nilai'],
        ],
        [
            'category' => 'Nilai',
            'roles' => ['pengajar'],
            'question' => 'Kesalahan umum pada file nilai Excel',
            'answer' => "File dapat ditolak bila bukan template aplikasi, kelas atau Mata Pelajaran tidak cocok, struktur LM/TP berubah, sheet salah, siswa tidak sesuai kelas, kolom hilang, atau nilai berada di luar 0 sampai 100.\n\nBaca pesan pada baris dan kolom yang disebutkan. Perbaiki file sumber atau unduh template baru, lalu upload ulang. Jangan menghapus pemeriksaan file dengan menyalin data ke format buatan sendiri.",
            'keywords' => ['excel ditolak', 'file tidak valid', 'kolom hilang', 'kelas tidak cocok', 'sheet salah', 'nilai di luar rentang'],
        ],

        [
            'category' => 'Kelas Wali',
            'roles' => ['admin'],
            'question' => 'Memahami pekerjaan Wali Kelas',
            'answer' => "Wali Kelas bekerja pada kelas yang ditugaskan untuk tahun ajaran aktif. Tugasnya mencakup data siswa kelas, absensi, ekstrakurikuler siswa, capaian kompetensi, catatan, pemeriksaan kelengkapan, dan rapor.\n\nAdmin menyiapkan kelas, penugasan, data dasar, periode, serta template. Nilai Mata Pelajaran tetap menjadi tanggung jawab Pengajar; Wali Kelas memantau dan meminta koreksi bila perlu.",
            'keywords' => ['tugas wali kelas', 'penugasan wali', 'monitor nilai', 'absensi', 'capaian kompetensi', 'rapor'],
        ],
        [
            'category' => 'Kelas Wali',
            'roles' => ['wali_kelas'],
            'question' => 'Siswa yang terlihat pada kelas Wali',
            'answer' => "Menu Siswa hanya menampilkan siswa dalam kelas yang menjadi tanggung jawab Anda pada tahun ajaran aktif. Gunakan pencarian dan filter untuk menemukan siswa. Wali Kelas dapat membuka, menambah, atau memperbarui siswa sesuai akses kelasnya.\n\nJika seorang siswa tidak terlihat, periksa tahun ajaran, semester, kelas wali, pencarian, dan filter. Jangan menambahkan duplikat sebelum Admin memastikan penempatan siswa.",
            'keywords' => ['siswa wali kelas', 'daftar siswa', 'siswa tidak muncul', 'filter siswa', 'kelas wali'],
        ],
        [
            'category' => 'Kelas Wali',
            'roles' => ['wali_kelas'],
            'question' => 'Mengisi Data Absensi',
            'answer' => "Buka Absensi lalu isi jumlah Sakit, Izin, dan Tanpa Keterangan untuk setiap siswa. Angka yang belum diubah tidak boleh dianggap sudah tersimpan. Klik Simpan setelah selesai.\n\nAbsensi dipakai pada rapor. Jika daftar kosong, periksa kelas dan konteks tahun ajaran sebelum meminta Admin mengubah data siswa.",
            'keywords' => ['absensi', 'kehadiran', 'sakit', 'izin', 'tanpa keterangan', 'simpan absensi'],
        ],
        [
            'category' => 'Kelas Wali',
            'roles' => ['wali_kelas'],
            'question' => 'Mengisi Ekstrakurikuler siswa',
            'answer' => "Buka Ekstrakurikuler, pilih kegiatan untuk siswa, isi keterangan atau nilai yang tersedia, lalu klik Simpan. Kegiatan yang sama tidak dapat dipilih dua kali untuk siswa yang sama.\n\nDaftar kegiatan disiapkan Admin. Jika kegiatan belum tersedia, hubungi Admin dan jangan menggantinya dengan kegiatan lain hanya agar form dapat disimpan.",
            'keywords' => ['ekstrakurikuler wali', 'nilai ekstrakurikuler', 'kegiatan siswa', 'duplikat ekstrakurikuler'],
        ],
        [
            'category' => 'Kelas Wali',
            'roles' => ['wali_kelas'],
            'question' => 'Mengelola Capaian Kompetensi',
            'answer' => "Capaian Kompetensi dibuat dari Nilai Akhir Rapor dan dapat disesuaikan oleh Wali Kelas. Pilih Mata Pelajaran, periksa Capaian Tertinggi dan Capaian Terendah, lalu ubah kalimat per siswa bila diperlukan.\n\nKalimat yang mengikuti default akan berubah ketika pengaturan kalimat awal diperbarui. Kalimat khusus siswa tidak mengikuti default sampai dikembalikan. Klik Simpan semua perubahan setelah meninjau hasilnya.",
            'keywords' => ['capaian kompetensi', 'capaian tertinggi', 'capaian terendah', 'kalimat default', 'simpan semua perubahan'],
        ],
        [
            'category' => 'Kelas Wali',
            'roles' => ['wali_kelas'],
            'question' => 'Template rentang Capaian Kompetensi',
            'answer' => "Template Range Capaian Kompetensi menentukan kalimat berdasarkan batas nilai minimum dan maksimum. Pastikan rentang tidak terbalik atau saling membingungkan, lalu klik Simpan Template.\n\nGunakan Reset ke Default hanya bila ingin mengembalikan pengaturan bawaan. Tinjau kembali capaian siswa setelah mengubah rentang.",
            'keywords' => ['range capaian', 'rentang nilai', 'template kalimat', 'reset default', 'nilai minimum maksimum'],
        ],
        [
            'category' => 'Kelas Wali',
            'roles' => ['wali_kelas'],
            'question' => 'Catatan Mata Pelajaran dan Catatan Siswa',
            'answer' => "Catatan Mata Pelajaran menyediakan Catatan Umum, Catatan UTS, dan Catatan UAS untuk siswa pada mapel yang dipilih. Catatan Siswa menyediakan catatan umum Wali Kelas. Isi dengan bahasa singkat, jelas, dan sesuai kebutuhan sekolah.\n\nKlik Simpan Semua Catatan atau Simpan Catatan pada halaman terkait. Catatan UTS dan UAS muncul sesuai bagian yang didukung template rapor.",
            'keywords' => ['catatan mata pelajaran', 'catatan siswa', 'catatan uts', 'catatan uas', 'simpan catatan'],
        ],
        [
            'category' => 'Kelas Wali',
            'roles' => ['wali_kelas'],
            'question' => 'Memantau progres nilai tanpa mengubah nilai Pengajar',
            'answer' => "Dashboard dan halaman Rapor membantu Wali Kelas melihat progres kelas dan jumlah Mata Pelajaran yang sudah memiliki nilai. Status Sebagian atau Belum Ada Nilai menunjukkan bagian yang perlu ditindaklanjuti.\n\nWali Kelas tidak mengubah nilai Mata Pelajaran dari halaman rapor. Minta Pengajar terkait memperbaiki atau melengkapi nilai. Jika Anda juga menjadi Pengajar, beralih ke peran Pengajar untuk mengedit nilai yang memang ditugaskan kepada Anda.",
            'keywords' => ['progres kelas', 'monitor nilai', 'nilai belum lengkap', 'wali edit nilai', 'beralih pengajar'],
        ],
        [
            'category' => 'Kelas Wali',
            'roles' => ['wali_kelas'],
            'question' => 'Informasi dan notifikasi Wali Kelas',
            'answer' => "Panel Informasi menampilkan pemberitahuan untuk akun Wali Kelas. Anda dapat melihat jumlah yang belum dibaca, menandai semua sebagai dibaca, dan menghapus pemberitahuan milik sendiri bila tindakan tersebut tersedia.\n\nMenghapus notifikasi tidak menghapus nilai, siswa, atau rapor. Gunakan halaman sumber untuk memeriksa kondisi data sebenarnya.",
            'keywords' => ['notifikasi wali', 'informasi', 'belum dibaca', 'tandai dibaca', 'hapus notifikasi'],
        ],

        [
            'category' => 'Rapor',
            'roles' => ['admin', 'wali_kelas'],
            'question' => 'Perbedaan UTS, UAS, Ganjil, dan Genap',
            'answer' => "Ganjil dan Genap adalah semester. UTS dan UAS adalah jenis rapor yang dapat dibuat di dalam semester aktif. Karena itu, UAS tidak sama dengan Semester Genap.\n\nContoh: jika semester aktif Ganjil dan Admin membuka UAS, Wali Kelas mengakses UAS Semester Ganjil. Perubahan semester dilakukan melalui alur Tahun Ajaran, bukan dengan memilih UTS atau UAS.",
            'keywords' => ['beda uts uas', 'uas bukan genap', 'semester ganjil', 'semester genap', 'jenis rapor'],
        ],
        [
            'category' => 'Rapor',
            'roles' => ['admin'],
            'question' => 'Memilih Jenis Rapor yang Dibuka',
            'answer' => "Di Format Rapor, pilih UTS atau UAS pada bagian Jenis Rapor yang Dibuka untuk Wali Kelas, lalu simpan. Pilihan ini menentukan satu jenis rapor yang dapat disiapkan, dicetak, dan diunduh Wali Kelas pada saat itu.\n\nPilihan tersebut berlaku pada konteks tahun ajaran aktif dan tidak mengubah semester. Pastikan template yang sesuai sudah aktif sebelum membuka periode untuk Wali Kelas.",
            'keywords' => ['jenis rapor dibuka', 'buka uts', 'buka uas', 'wali kelas', 'format rapor'],
        ],
        [
            'category' => 'Rapor',
            'roles' => ['wali_kelas'],
            'question' => 'Rapor yang dapat diakses Wali Kelas',
            'answer' => "Halaman Rapor menampilkan jenis yang sedang dibuka Admin. Tab jenis lain bertanda Belum dibuka dan tidak dapat digunakan. Jika template belum aktif, halaman menampilkan pesan agar Anda menghubungi Admin.\n\nJangan mengganti jenis pada alamat halaman. Sistem tetap memeriksa jenis rapor, tahun ajaran, semester, kelas wali, dan siswa yang berwenang.",
            'keywords' => ['rapor belum dibuka', 'tab uts', 'tab uas', 'template belum aktif', 'akses wali'],
        ],
        [
            'category' => 'Rapor',
            'roles' => ['admin', 'pengajar', 'wali_kelas'],
            'question' => 'Nilai yang dipakai pada Rapor UTS',
            'answer' => "Rapor UTS memakai Nilai Akhir Rapor terbaru yang tersedia. Sebelum nilai akhir semester tersedia, perhitungan dapat memakai komponen TP dan LM yang sudah diisi. Setelah Nilai Tes dan Nilai Non-Tes tersedia, hasil terbaru dapat ikut membentuk Nilai Akhir Rapor.\n\nKarena nilainya dinamis, koreksi yang disimpan Pengajar dapat terlihat pada rapor UTS yang dibuat ulang. UTS tidak membuat salinan nilai tetap saat pertama kali dicetak.",
            'keywords' => ['nilai uts', 'nilai akhir rapor', 'uts dinamis', 'tp lm', 'nilai terbaru', 'buat ulang uts'],
        ],
        [
            'category' => 'Rapor',
            'roles' => ['admin', 'pengajar', 'wali_kelas'],
            'question' => 'Syarat nilai untuk Rapor UAS',
            'answer' => "Rapor UAS lebih ketat. Nilai Mata Pelajaran harus berstatus Lengkap dan memiliki hasil akhir semester agar dapat dipakai. Pengajar perlu mengisi TP, LM, Nilai Tes, dan Nilai Non-Tes, lalu menyimpannya sampai status siswa menjadi Lengkap.\n\nJika sebuah mapel belum lengkap, mapel tersebut belum memenuhi syarat UAS. Wali Kelas perlu meminta Pengajar menyelesaikan data pada kelas dan periode yang benar.",
            'keywords' => ['syarat uas', 'nilai uas', 'status lengkap', 'nilai akhir semester', 'mapel belum memenuhi syarat'],
        ],
        [
            'category' => 'Rapor',
            'roles' => ['admin', 'wali_kelas'],
            'question' => 'Arti status Lengkap, Sebagian, dan Belum Ada Nilai pada rapor',
            'answer' => "Lengkap berarti seluruh Mata Pelajaran pada konteks rapor memiliki nilai yang memenuhi syarat. Sebagian berarti setidaknya satu mapel memenuhi syarat, tetapi masih ada mapel yang belum siap. Belum Ada Nilai berarti belum ada satu pun mapel yang dapat dipakai.\n\nRapor Sebagian tetap dapat dibuat; bagian mapel yang belum siap dapat tampil kosong. Jika Belum Ada Nilai, minta Pengajar mengisi nilai terlebih dahulu karena rapor tidak dapat dibuat tanpa setidaknya satu mapel yang memenuhi syarat.",
            'keywords' => ['status rapor', 'lengkap', 'sebagian', 'belum ada nilai', 'rapor parsial', 'mapel kosong'],
        ],
        [
            'category' => 'Rapor',
            'roles' => ['wali_kelas'],
            'question' => 'Filter Siap Cetak dan status kehadiran',
            'answer' => "Tombol Siap Cetak menyaring daftar ke siswa yang sudah memiliki nilai yang dapat dipakai dan data kehadiran. Klik lagi saat bertuliskan Semua Siswa untuk kembali melihat seluruh kelas.\n\nFilter ini membantu pemeriksaan, tetapi bukan pengganti status per Mata Pelajaran. Buka tooltip atau rincian status untuk mengetahui bagian yang belum lengkap.",
            'keywords' => ['siap cetak', 'semua siswa', 'filter rapor', 'status kehadiran', 'status nilai'],
        ],
        [
            'category' => 'Rapor',
            'roles' => ['admin', 'pengajar', 'wali_kelas'],
            'question' => 'Perubahan data setelah rapor pernah dibuat',
            'answer' => "Perubahan nilai, identitas siswa, Profile Sekolah, penandatangan, atau template dapat membuat dokumen lama tidak lagi mewakili data terbaru. Setelah perubahan disimpan, siapkan atau unduh ulang rapor yang diperlukan.\n\nPengajar harus memperbaiki nilai dari halaman Input Nilai. Wali Kelas memeriksa hasil baru pada halaman Rapor. Admin dapat meninjau Riwayat Cetak Rapor untuk dokumen yang tercatat.",
            'keywords' => ['rapor berubah', 'buat ulang rapor', 'nilai terbaru', 'identitas siswa', 'profil sekolah', 'riwayat cetak'],
        ],
        [
            'category' => 'Rapor',
            'roles' => ['admin'],
            'question' => 'Riwayat Cetak Rapor',
            'answer' => "Riwayat Cetak Rapor menampilkan dokumen yang tercatat pernah dibuat. Admin dapat membuka preview, mengunduh, membuat ulang, atau menghapus riwayat melalui tindakan yang tersedia.\n\nMembuat ulang memakai data dan konteks rapor yang masih valid. Jika template atau data pendukung tidak tersedia, proses dapat ditolak. Menghapus riwayat harus dikonfirmasi karena file terkait dapat ikut dihapus.",
            'keywords' => ['riwayat cetak rapor', 'preview riwayat', 'download riwayat', 'regenerate', 'buat ulang', 'hapus riwayat'],
        ],

        [
            'category' => 'Download & Cetak',
            'roles' => ['wali_kelas'],
            'question' => 'Mengunduh satu rapor DOCX',
            'answer' => "Pada halaman Rapor, gunakan tombol DOCX pada baris siswa. Aplikasi menyiapkan atau memakai dokumen terbaru yang masih sesuai dengan data, template, tahun ajaran, semester, dan jenis rapor.\n\nJika unduhan tidak dimulai, pastikan template aktif dan setidaknya satu Mata Pelajaran memenuhi syarat. Coba ulang setelah koreksi nilai atau data disimpan. Jangan membagikan tautan unduhan kepada orang yang tidak berwenang.",
            'keywords' => ['download docx', 'unduh rapor', 'rapor word', 'satu siswa', 'dokumen tidak terunduh'],
        ],
        [
            'category' => 'Download & Cetak',
            'roles' => ['wali_kelas'],
            'question' => 'Preview dan cetak rapor dari browser',
            'answer' => "Gunakan Preview atau Cetak HTML untuk membuka tampilan rapor di browser. Dari dialog cetak browser, pilih printer atau Simpan sebagai PDF bila pilihan tersebut tersedia pada perangkat.\n\nPeriksa ukuran kertas, orientasi, margin, dan halaman sebelum mencetak. Tampilan browser merupakan alternatif saat tombol PDF aplikasi tidak tersedia; DOCX tetap dapat diunduh secara terpisah.",
            'keywords' => ['cetak html', 'print browser', 'preview rapor', 'simpan sebagai pdf', 'print rapor'],
        ],
        [
            'category' => 'Download & Cetak',
            'roles' => ['admin', 'wali_kelas'],
            'question' => 'Kapan pilihan PDF aplikasi tersedia?',
            'answer' => "Pilihan PDF aplikasi hanya tampil bila layanan pada server mendukungnya. Jika dukungan tersebut tidak tersedia, kolom status dan tombol PDF tidak ditampilkan; ini bukan tanda DOCX atau cetak browser rusak.\n\nGunakan DOCX atau Cetak HTML sebagai pilihan utama. Pada lingkungan yang mendukung PDF, dokumen PDF yang sudah siap dapat digunakan kembali, sedangkan dokumen yang belum ada perlu disiapkan oleh sistem.",
            'keywords' => ['pdf tidak ada', 'tombol pdf hilang', 'status pdf', 'alternatif pdf', 'docx', 'cetak html'],
        ],
        [
            'category' => 'Download & Cetak',
            'roles' => ['wali_kelas'],
            'question' => 'Unduh Semua Rapor dalam ZIP',
            'answer' => "Klik Unduh Semua Rapor pada halaman Rapor. Aplikasi meminta konfirmasi agar periode tidak salah. Setelah Anda memilih Unduh Semua Rapor, dokumen DOCX siswa disiapkan satu per satu dan progres ditampilkan. Setelah itu, dokumen yang siap dikemas menjadi satu file ZIP.\n\nJangan menutup halaman atau mengganti periode saat proses berjalan. Satu klik hanya memproses siswa dalam kelas wali dan konteks rapor yang sedang dibuka.",
            'keywords' => ['unduh semua rapor', 'batch docx', 'zip rapor', 'konfirmasi download', 'progres menyiapkan'],
        ],
        [
            'category' => 'Download & Cetak',
            'roles' => ['wali_kelas'],
            'question' => 'Hasil sebagian pada Unduh Semua Rapor',
            'answer' => "Jika sebagian siswa berhasil, ZIP tetap diunduh dan pesan menampilkan jumlah rapor yang disertakan serta yang belum tersedia. Aplikasi memakai hasil akhir dari server, bukan hanya hitungan pada layar.\n\nJika tidak ada satu pun DOCX yang siap, ZIP tidak dibuat. Periksa template, jenis rapor yang dibuka, nilai, dan siswa yang disebut belum tersedia, lalu coba lagi. Kegagalan satu siswa tidak otomatis menghentikan persiapan siswa berikutnya.",
            'keywords' => ['batch sebagian', 'rapor tidak masuk zip', 'zero success', 'tidak ada docx', 'siswa unavailable'],
        ],
        [
            'category' => 'Download & Cetak',
            'roles' => ['admin', 'wali_kelas'],
            'question' => 'Keamanan dan masa berlaku file batch rapor',
            'answer' => "ZIP batch disimpan sementara dan hanya dikirim melalui tautan yang terikat pada akun Wali Kelas yang membuatnya. Pengguna lain tidak dapat memakai tautan tersebut. Nama file di dalam ZIP memuat penanda siswa agar dua siswa dengan nama sama tidak saling menimpa.\n\nUnduh ZIP segera setelah proses selesai. File sementara dibersihkan otomatis setelah melewati masa simpan; buat batch baru bila tautan lama sudah tidak berlaku.",
            'keywords' => ['zip aman', 'tautan kedaluwarsa', 'file sementara', 'nama siswa sama', 'batch cleanup', 'download privat'],
        ],

        [
            'category' => 'Template Rapor',
            'roles' => ['admin'],
            'question' => 'Fungsi Template Rapor',
            'answer' => "Template Rapor adalah file DOCX yang menentukan susunan dan tempat data siswa pada dokumen. Template terikat pada jenis UTS atau UAS, tahun ajaran, semester, serta kelas yang dipilih atau cakupan Global.\n\nGunakan panduan placeholder dan contoh template dari halaman Format Rapor. Jangan menghapus atau mengubah penanda data tanpa memahami bagian yang akan hilang dari dokumen.",
            'keywords' => ['template rapor', 'format rapor', 'docx', 'placeholder', 'contoh template', 'tutorial template'],
        ],
        [
            'category' => 'Template Rapor',
            'roles' => ['admin'],
            'question' => 'Upload dan pemeriksaan template UTS/UAS',
            'answer' => "Upload hanya menerima file DOCX dengan ukuran paling besar 10 MB. Pilih UTS atau UAS, tahun ajaran, semester, serta kelas yang menggunakan template. Tanpa pilihan kelas, template menjadi Global.\n\nTemplate UTS harus memuat teks RAPOR TENGAH SEMESTER. Template UAS ditolak bila masih memuat teks tersebut. Aplikasi juga memeriksa apakah file dapat dibaca dan apakah placeholder wajib tersedia. Baca pesan pemeriksaan sebelum mencoba lagi.",
            'keywords' => ['upload template', 'docx 10 mb', 'rapor tengah semester', 'template uts', 'template uas', 'file ditolak'],
        ],
        [
            'category' => 'Template Rapor',
            'roles' => ['admin'],
            'question' => 'Template khusus kelas, Global, dan beberapa template aktif',
            'answer' => "Template aktif yang khusus untuk kelas dipakai lebih dahulu. Jika tidak ada yang sesuai, aplikasi mencari template Global pada jenis, tahun ajaran, dan semester yang sama.\n\nBeberapa template dapat berstatus aktif. Bila lebih dari satu template aktif cocok pada cakupan yang sama, template yang paling baru diperbarui dipilih. Agar hasil mudah diprediksi, nonaktifkan template lama yang tidak lagi digunakan dan cek Preview sebelum membuka rapor.",
            'keywords' => ['template kelas', 'template global', 'beberapa template aktif', 'template terbaru', 'prioritas template'],
        ],
        [
            'category' => 'Template Rapor',
            'roles' => ['admin', 'wali_kelas'],
            'question' => 'Jika template rapor belum tersedia',
            'answer' => "Wali Kelas melihat pesan Template Periode Dibuka Belum Tersedia atau Template belum aktif dan tidak dapat menyiapkan rapor pada konteks tersebut. Admin perlu membuka Format Rapor, memeriksa jenis, tahun ajaran, semester, kelas, serta status aktif template.\n\nSetelah template yang sesuai diaktifkan, muat ulang halaman Rapor. Jangan memakai template jenis atau periode lain sebagai pengganti.",
            'keywords' => ['template belum tersedia', 'template belum aktif', 'tidak bisa generate rapor', 'hubungi admin', 'muat ulang'],
        ],
        [
            'category' => 'Template Rapor',
            'roles' => ['admin'],
            'question' => 'Dampak mengganti atau menghapus template',
            'answer' => "Aktivasi, penonaktifan, perubahan, atau penghapusan template memengaruhi rapor yang dibuat sesudahnya pada kelas dan periode terkait. Dokumen baru akan mengikuti template aktif yang dipilih aplikasi.\n\nSebelum menghapus, periksa kelas dan jenis template lalu baca konfirmasi. Setelah mengganti template, gunakan Preview dan buat ulang dokumen yang memang harus memakai format baru.",
            'keywords' => ['ganti template', 'hapus template', 'aktifkan template', 'preview template', 'buat ulang rapor'],
        ],

        [
            'category' => 'Email & Pemulihan',
            'roles' => ['admin', 'pengajar', 'wali_kelas'],
            'question' => 'Menggunakan Lupa password?',
            'answer' => "Pada halaman Masuk, klik Lupa password?, masukkan email yang terdaftar, lalu kirim permintaan. Pesan yang tampil selalu sama, baik alamat memenuhi syarat maupun tidak, agar informasi akun tidak dapat ditebak.\n\nAdmin dapat memakai email akun Admin. Guru hanya menerima tautan pemulihan bila emailnya tersedia dan sudah Terverifikasi. Tautan dikirim ke email dan tidak membuat akun baru.",
            'keywords' => ['lupa password', 'lupa kata sandi', 'reset password', 'email reset', 'tidak bisa login'],
        ],
        [
            'category' => 'Email & Pemulihan',
            'roles' => ['admin'],
            'question' => 'Pemulihan password Admin melalui email',
            'answer' => "Gunakan Lupa password? pada halaman Masuk dan isi email Admin. Buka tautan yang diterima, masukkan email yang sama, password baru minimal 8 karakter, dan konfirmasi password.\n\nSetelah berhasil, Anda tidak langsung masuk. Kembali ke halaman Masuk dan gunakan password baru. Tautan hanya dapat dipakai sekali dan akan kedaluwarsa. Proses ini tidak membuka setup awal dan tidak membuat Admin kedua.",
            'keywords' => ['reset admin', 'email admin', 'tautan pemulihan', 'password baru admin', 'satu admin'],
        ],
        [
            'category' => 'Email & Pemulihan',
            'roles' => ['pengajar', 'wali_kelas'],
            'question' => 'Memverifikasi email Guru',
            'answer' => "Jika email tersedia tetapi belum terverifikasi, gunakan tombol Verifikasi Email pada pengingat akun. Admin juga dapat mengirim tautan dari status Belum diverifikasi di Data Pengajar setelah memastikan alamat benar. Menyimpan data Guru saja tidak mengirim email otomatis.\n\nBuka tautan saat masuk dengan akun Guru yang terkait. Tautan harus masih berlaku dan sesuai dengan alamat email saat ini. Keberhasilan ditandai pesan Email berhasil diverifikasi.",
            'keywords' => ['verifikasi email guru', 'kirim verifikasi', 'belum diverifikasi', 'email berhasil diverifikasi', 'resend'],
        ],
        [
            'category' => 'Email & Pemulihan',
            'roles' => ['pengajar', 'wali_kelas'],
            'question' => 'Membuka tautan verifikasi dengan akun yang salah',
            'answer' => "Tautan verifikasi hanya dapat digunakan oleh Guru yang ID akun dan email saat ini cocok dengan tautan. Jika belum masuk, aplikasi meminta Anda masuk sebagai Guru terkait. Jika Admin atau Guru lain sedang masuk, verifikasi ditolak dan pesan penjelasan ditampilkan.\n\nKeluar dari akun yang salah, masuk dengan akun Guru yang benar, lalu buka kembali tautan selama masih berlaku. Jangan meneruskan tautan kepada orang lain.",
            'keywords' => ['tautan verifikasi salah akun', 'admin membuka link guru', 'guru lain', 'login guru terkait', 'verifikasi ditolak'],
        ],
        [
            'category' => 'Email & Pemulihan',
            'roles' => ['pengajar', 'wali_kelas'],
            'question' => 'Reset password Guru dengan email terverifikasi',
            'answer' => "Guru dengan email Terverifikasi dapat meminta pemulihan dari Lupa password?. Buka tautan email, masukkan alamat yang sama, password baru, dan konfirmasinya. Setelah berhasil, masuk kembali melalui halaman Masuk.\n\nPassword lama tidak dapat digunakan lagi dan tautan yang sudah dipakai tidak dapat digunakan ulang. Pemulihan ini hanya mengubah akun Guru yang sesuai dan tidak memengaruhi akun Admin.",
            'keywords' => ['reset password guru', 'email terverifikasi', 'password lama', 'tautan sekali pakai', 'login guru'],
        ],
        [
            'category' => 'Email & Pemulihan',
            'roles' => ['admin', 'pengajar', 'wali_kelas'],
            'question' => 'Guru tanpa email terverifikasi lupa password',
            'answer' => "Guru tanpa email, dengan email Belum diverifikasi, atau yang tidak dapat membuka email tidak menerima pemulihan mandiri. Hubungi Admin sekolah.\n\nAdmin dapat menetapkan password sementara dari Data Pengajar. Guru kemudian masuk melalui halaman Masuk dan wajib membuat password baru. Email tetap opsional dan tidak boleh ditandai terverifikasi tanpa membuka tautan verifikasi.",
            'keywords' => ['guru tanpa email', 'email belum diverifikasi', 'hubungi admin', 'reset bantuan admin', 'password sementara'],
        ],
        [
            'category' => 'Email & Pemulihan',
            'roles' => ['admin', 'pengajar', 'wali_kelas'],
            'question' => 'Email verifikasi atau reset belum diterima',
            'answer' => "Periksa folder Spam atau Junk, pastikan alamat email pada akun benar, lalu tunggu sebentar sebelum meminta kirim ulang. Hindari menekan tombol berulang kali karena permintaan dibatasi untuk melindungi akun.\n\nJika alamat Guru salah, minta Admin memperbaruinya. Setelah alamat berubah, Guru perlu memverifikasi alamat baru. Jika email tetap tidak datang, hubungi Admin untuk memeriksa data akun dan layanan email sekolah.",
            'keywords' => ['email tidak masuk', 'spam', 'junk', 'kirim ulang', 'reset tidak diterima', 'alamat email salah'],
        ],
        [
            'category' => 'Email & Pemulihan',
            'roles' => ['admin', 'pengajar', 'wali_kelas'],
            'question' => 'Tautan pemulihan atau verifikasi tidak berlaku',
            'answer' => "Tautan dapat ditolak karena sudah kedaluwarsa, pernah dipakai, tanda pengamannya tidak cocok, akun yang masuk salah, atau email Guru sudah berubah. Gunakan permintaan terbaru dan pastikan alamat pada akun masih sama.\n\nUntuk pemulihan password, kembali ke Lupa password? dan kirim permintaan baru. Untuk verifikasi Guru, gunakan Verifikasi Email atau minta Admin mengirim ulang. Jangan mengubah bagian alamat tautan secara manual.",
            'keywords' => ['link expired', 'tautan kedaluwarsa', 'tautan invalid', 'reset gagal', 'verifikasi gagal', 'kirim ulang'],
        ],

        [
            'category' => 'Masalah Umum',
            'roles' => ['admin', 'pengajar', 'wali_kelas'],
            'question' => 'Username, email, atau password ditolak',
            'answer' => "Masalah: Anda tidak dapat masuk.\n\nPenyebab yang mungkin:\n- Username atau email tidak sama dengan data akun.\n- Password salah.\n- Identifier yang sama tercatat pada dua akun sehingga sistem menolak pilihan yang ambigu.\n- Guru sedang memakai password sementara dan perlu melanjutkan pergantian password.\n\nYang harus dilakukan:\nKetik ulang tanpa spasi tambahan. Gunakan Lupa password? bila email memenuhi syarat. Guru tanpa email terverifikasi perlu menghubungi Admin.",
            'keywords' => ['tidak bisa login', 'password salah', 'username ditolak', 'email ditolak', 'akun ambigu'],
        ],
        [
            'category' => 'Masalah Umum',
            'roles' => ['admin', 'wali_kelas'],
            'question' => 'Data tidak muncul atau berada pada periode yang salah',
            'answer' => "Masalah: kelas, siswa, nilai, atau rapor yang dicari tidak terlihat.\n\nPenyebab yang mungkin:\n- Tahun ajaran atau semester yang dipilih berbeda.\n- Pencarian, filter, atau halaman daftar masih aktif.\n- Data berada di arsip.\n- Penugasan kelas tidak sesuai konteks aktif.\n\nYang harus dilakukan:\nPeriksa pemilih Tahun Ajaran, semester, kelas, dan jenis rapor. Reset pencarian serta filter. Admin dapat memeriksa arsip dan penugasan sebelum membuat data baru.",
            'keywords' => ['data tidak muncul', 'periode salah', 'tahun ajaran salah', 'filter', 'arsip', 'kelas tidak terlihat'],
        ],
        [
            'category' => 'Masalah Umum',
            'roles' => ['admin'],
            'question' => 'Form ditolak karena data duplikat atau tidak lengkap',
            'answer' => "Masalah: formulir tidak dapat disimpan.\n\nPenyebab yang mungkin:\n- Kolom bertanda wajib belum diisi.\n- Username, email, NIS, NISN, atau nama tahun ajaran sudah digunakan.\n- Tanggal, angka, atau pilihan tidak sesuai format.\n- Data yang sama berada di arsip.\n\nYang harus dilakukan:\nBaca pesan di bawah kolom, perbaiki hanya bagian yang ditandai, lalu kirim ulang. Cari data lama dan periksa arsip sebelum membuat salinan baru.",
            'keywords' => ['validasi gagal', 'data duplikat', 'kolom wajib', 'username sudah digunakan', 'nisn duplikat'],
        ],
        [
            'category' => 'Masalah Umum',
            'roles' => ['admin', 'pengajar'],
            'question' => 'Data tidak dapat dihapus',
            'answer' => "Masalah: tombol hapus ditolak atau menampilkan data terkait.\n\nPenyebab yang mungkin:\nData masih dipakai oleh kelas, penugasan, LM/TP, nilai, siswa, rapor, atau periode akademik. Data induk juga dapat diperlukan sebelum data anak dipulihkan.\n\nYang harus dilakukan:\nBaca pemeriksaan keterkaitan. Untuk koreksi, edit data bila lebih aman. Gunakan Recycle Bin dan Pulihkan sesuai urutan induk-anak. Jangan memaksa hapus permanen pada data aktif.",
            'keywords' => ['tidak bisa hapus', 'data terkait', 'dependency', 'recycle bin', 'pulihkan induk'],
        ],
        [
            'category' => 'Masalah Umum',
            'roles' => ['pengajar'],
            'question' => 'Nilai tidak tersimpan atau status masih Belum Lengkap',
            'answer' => "Masalah: perubahan nilai tidak terlihat atau status tetap Belum Lengkap.\n\nPenyebab yang mungkin:\n- Tombol Simpan belum ditekan.\n- Masih ada TP, LM, Nilai Tes, atau Nilai Non-Tes yang kosong.\n- Nilai berada di luar 0 sampai 100.\n- Halaman atau file Excel memakai struktur lama.\n\nYang harus dilakukan:\nLengkapi kolom yang diperlukan, perbaiki pesan merah, klik Simpan, lalu muat ulang. Jika LM/TP berubah, unduh template Excel baru.",
            'keywords' => ['nilai tidak tersimpan', 'belum lengkap', 'nilai error', 'klik simpan', 'struktur lama'],
        ],
        [
            'category' => 'Masalah Umum',
            'roles' => ['pengajar'],
            'question' => 'Template atau upload nilai Excel bermasalah',
            'answer' => "Masalah: template tidak dapat diunduh atau file tidak dapat dimuat.\n\nPenyebab yang mungkin:\n- LM/TP belum lengkap.\n- File bukan template terbaru dari aplikasi.\n- Kelas, mapel, siswa, sheet, atau kolom tidak cocok.\n- Preview sudah kedaluwarsa.\n\nYang harus dilakukan:\nLengkapi LM/TP, unduh template baru, jangan ubah struktur file, lalu upload ulang. Pada workbook banyak sheet, simpan sheet saat ini sebelum melanjutkan.",
            'keywords' => ['excel bermasalah', 'template tidak bisa download', 'upload gagal', 'preview kedaluwarsa', 'sheet'],
        ],
        [
            'category' => 'Masalah Umum',
            'roles' => ['admin', 'wali_kelas'],
            'question' => 'Rapor belum siap atau tidak dapat dibuat',
            'answer' => "Masalah: tombol rapor tidak tersedia, dokumen gagal dibuat, atau status Belum Ada Nilai.\n\nPenyebab yang mungkin:\n- Admin belum membuka jenis rapor tersebut.\n- Template yang sesuai belum aktif.\n- Tidak ada satu pun Mata Pelajaran yang memenuhi syarat.\n- Tahun ajaran, semester, kelas, atau siswa tidak cocok.\n\nYang harus dilakukan:\nPeriksa jenis rapor dan template. Wali Kelas meminta Pengajar melengkapi nilai; Admin memeriksa konteks serta penugasan. Muat ulang setelah koreksi disimpan.",
            'keywords' => ['rapor belum siap', 'gagal generate', 'belum ada nilai', 'template tidak aktif', 'periode belum dibuka'],
        ],
        [
            'category' => 'Masalah Umum',
            'roles' => ['wali_kelas'],
            'question' => 'DOCX, ZIP, atau cetak rapor bermasalah',
            'answer' => "Masalah: unduhan tidak dimulai, ZIP hanya berisi sebagian siswa, atau hasil cetak tidak sesuai.\n\nPenyebab yang mungkin:\n- Sebagian DOCX belum dapat disiapkan.\n- Tautan ZIP lama sudah tidak berlaku.\n- Browser memblokir unduhan atau pengaturan kertas belum sesuai.\n\nYang harus dilakukan:\nBaca jumlah berhasil dan belum tersedia, perbaiki data lalu jalankan Unduh Semua Rapor kembali. Izinkan unduhan dari aplikasi. Untuk cetak browser, periksa ukuran kertas, margin, orientasi, dan preview.",
            'keywords' => ['docx gagal', 'zip sebagian', 'download diblokir', 'link kedaluwarsa', 'hasil cetak'],
        ],
        [
            'category' => 'Masalah Umum',
            'roles' => ['admin'],
            'question' => 'File template rapor ditolak',
            'answer' => "Masalah: upload Format Rapor gagal.\n\nPenyebab yang mungkin:\n- File bukan DOCX yang valid atau lebih besar dari 10 MB.\n- Jenis UTS/UAS tidak sesuai teks di dalam file.\n- Placeholder wajib hilang atau format dokumen rusak.\n- Tahun ajaran, semester, atau kelas belum dipilih dengan benar.\n\nYang harus dilakukan:\nGunakan contoh dan panduan placeholder dari aplikasi. Cocokkan jenis template, perbaiki file, lalu upload dan Preview kembali.",
            'keywords' => ['template rapor ditolak', 'docx invalid', 'file terlalu besar', 'placeholder hilang', 'uts uas salah'],
        ],
        [
            'category' => 'Masalah Umum',
            'roles' => ['admin', 'pengajar', 'wali_kelas'],
            'question' => 'Halaman kedaluwarsa atau keluar otomatis',
            'answer' => "Masalah: halaman meminta masuk kembali atau pengiriman form ditolak karena sudah kedaluwarsa.\n\nPenyebab yang mungkin:\nSesi berakhir setelah tidak aktif, halaman lama masih terbuka, atau koneksi terputus saat form dikirim.\n\nYang harus dilakukan:\nBuka halaman Masuk, login kembali, lalu ulangi dari menu aplikasi. Periksa apakah perubahan sebelumnya sudah tersimpan. Hindari mengirim ulang form lama dari tombol Back tanpa memuat ulang halaman.",
            'keywords' => ['page expired', 'halaman kedaluwarsa', 'keluar otomatis', 'session timeout', 'csrf', 'login ulang'],
        ],
        [
            'category' => 'Masalah Umum',
            'roles' => ['pengajar', 'wali_kelas'],
            'question' => 'Menu tidak ada atau akses ditolak',
            'answer' => "Masalah: menu yang dibutuhkan tidak tampil atau halaman menolak akses.\n\nPenyebab yang mungkin:\n- Peran Guru yang dipilih tidak sesuai.\n- Akun belum ditugaskan pada kelas atau Mata Pelajaran tersebut.\n- Tahun ajaran aktif berbeda.\n- Password sementara belum diganti.\n\nYang harus dilakukan:\nPilih peran Pengajar atau Wali Kelas yang benar, selesaikan pergantian password bila diminta, lalu cek konteks tahun ajaran. Hubungi Admin bila penugasan belum sesuai.",
            'keywords' => ['akses ditolak', 'menu hilang', 'role salah', 'peran guru', 'penugasan belum ada'],
        ],

        [
            'category' => 'Keamanan Akun',
            'roles' => ['admin', 'pengajar', 'wali_kelas'],
            'question' => 'Menjaga password dan tautan pemulihan',
            'answer' => "Gunakan password yang tidak dipakai di layanan lain dan jangan membagikannya kepada rekan kerja. Jangan mengirim foto layar, kode, atau tautan pemulihan/verifikasi kepada orang lain.\n\nJika menerima email yang tidak Anda minta, jangan buka tautan mencurigakan. Masuk melalui alamat resmi aplikasi dan hubungi Admin sekolah. Ganti password segera bila akun diduga digunakan orang lain.",
            'keywords' => ['keamanan password', 'jangan bagikan password', 'tautan reset', 'akun dibajak', 'email mencurigakan'],
        ],
        [
            'category' => 'Keamanan Akun',
            'roles' => ['admin', 'pengajar', 'wali_kelas'],
            'question' => 'Aman memakai perangkat bersama',
            'answer' => "Pada komputer bersama, jangan simpan password di browser bila perangkat dapat dipakai orang lain. Klik Keluar setelah selesai dan tutup tab yang memuat data siswa atau rapor.\n\nUnduhan rapor berisi data pribadi. Simpan hanya di lokasi yang diizinkan sekolah, jangan membagikannya melalui tautan umum, dan hapus salinan dari perangkat bersama setelah dipindahkan dengan aman.",
            'keywords' => ['komputer bersama', 'logout', 'data pribadi siswa', 'file rapor', 'perangkat umum'],
        ],
        [
            'category' => 'Keamanan Akun',
            'roles' => ['admin', 'pengajar', 'wali_kelas'],
            'question' => 'Mengunggah file dengan aman',
            'answer' => "Upload hanya file yang memang diminta aplikasi, seperti template siswa, template nilai, atau template rapor. Periksa kembali file sebelum memilihnya dan jangan menyisipkan data rahasia yang tidak diperlukan.\n\nJika aplikasi menolak jenis, ukuran, atau isi file, perbaiki sumbernya. Jangan mengganti ekstensi file semata-mata agar terlihat sesuai.",
            'keywords' => ['upload aman', 'file sensitif', 'template excel', 'template docx', 'ekstensi file'],
        ],
    ],
];
