<?php

return [
    'admin' => [
        [
            'category' => 'Import Siswa',
            'question' => 'Cara import siswa dari Excel',
            'answer' => 'Buka Admin > Siswa, unduh template, isi data sesuai kolom, lalu upload file. Pastikan tahun ajaran aktif benar dan nama kelas sama dengan daftar kelas aktif.',
            'keywords' => ['import siswa', 'excel', 'upload', 'template', 'kelas', 'nis', 'nisn', 'siswa'],
        ],
        [
            'category' => 'Import Siswa',
            'question' => 'Kenapa import siswa gagal karena kelas tidak ditemukan',
            'answer' => 'Biasanya terjadi karena kelas di Excel belum dibuat atau tulisannya berbeda. Cek menu Kelas, lalu samakan kolom kelas dengan kelas pada tahun ajaran aktif.',
            'keywords' => ['kelas tidak ditemukan', 'import siswa', 'excel', 'kelas', 'tahun ajaran', 'upload'],
        ],
        [
            'category' => 'Import Siswa',
            'question' => 'Kenapa NIS atau NISN duplikat saat import',
            'answer' => 'NIS dan NISN harus unik. Cek apakah nomor sudah dipakai di data siswa atau muncul lebih dari sekali dalam file Excel, lalu perbaiki sebelum upload ulang.',
            'keywords' => ['nis', 'nisn', 'duplikat', 'duplicate', 'import siswa', 'excel', 'validasi'],
        ],
        [
            'category' => 'Import Siswa',
            'question' => 'Apa yang harus dilakukan sebelum import siswa',
            'answer' => 'Pastikan profil sekolah, tahun ajaran aktif, semester aktif, dan kelas sudah dibuat. Gunakan template terbaru agar kolom dan format data sesuai.',
            'keywords' => ['sebelum import', 'import siswa', 'template', 'tahun ajaran', 'semester', 'kelas'],
        ],
        [
            'category' => 'Import Siswa',
            'question' => 'Cara download template import siswa',
            'answer' => 'Buka Admin > Siswa, lalu pilih download template import. Template berisi kolom wajib, contoh data, dan daftar kelas pada tahun ajaran aktif.',
            'keywords' => ['download template', 'template siswa', 'import siswa', 'excel', 'daftar kelas'],
        ],
        [
            'category' => 'Kelas',
            'question' => 'Cara membuat kelas',
            'answer' => 'Buka Admin > Kelas > Tambah Data. Isi nomor kelas, nama kelas, dan tahun ajaran. Wali kelas diatur dari menu Pengajar, bukan dari form kelas.',
            'keywords' => ['kelas', 'buat kelas', 'tambah kelas', 'rombel', 'tahun ajaran'],
        ],
        [
            'category' => 'Pengajar',
            'question' => 'Cara mengatur wali kelas',
            'answer' => 'Buka Admin > Pengajar, tambah atau edit guru, pilih jabatan Wali Kelas, lalu pilih kelas wali. Pastikan kelasnya berada di tahun ajaran aktif.',
            'keywords' => ['wali kelas', 'guru', 'pengajar', 'kelas wali', 'assignment'],
        ],
        [
            'category' => 'Pengajar',
            'question' => 'Cara membuat akun guru',
            'answer' => 'Buka Admin > Pengajar > Tambah Data. Isi identitas guru, username, password, jabatan, dan tanggung jawab kelas atau mapel sesuai peran guru.',
            'keywords' => ['akun guru', 'buat guru', 'pengajar', 'username', 'password', 'wali kelas'],
        ],
        [
            'category' => 'Mata Pelajaran',
            'question' => 'Cara mengatur mata pelajaran',
            'answer' => 'Buka Admin > Pelajaran, pilih kelas, jenis mapel, dan guru pengampu. Untuk mapel wajib reguler pilih wali kelas; untuk spesialis pilih guru yang ditugaskan pada kelas itu.',
            'keywords' => ['mata pelajaran', 'mapel', 'guru pengampu', 'muatan lokal', 'spesialis', 'wali kelas'],
        ],
        [
            'category' => 'Mata Pelajaran',
            'question' => 'Kenapa guru tidak muncul saat memilih pengajar mapel',
            'answer' => 'Biasanya guru belum ditugaskan mengajar kelas tersebut atau jenis mapelnya tidak sesuai. Cek tanggung jawab guru di menu Pengajar, lalu pilih kelas yang tepat.',
            'keywords' => ['guru tidak muncul', 'pengajar mapel', 'mata pelajaran', 'kelas mengajar', 'muatan lokal', 'spesialis'],
        ],
        [
            'category' => 'Tahun Ajaran',
            'question' => 'Cara mengatur tahun ajaran aktif',
            'answer' => 'Buka Admin > Tahun Ajaran, lalu aktifkan tahun ajaran dan semester yang sedang digunakan. Semua input data mengikuti konteks tahun ajaran aktif.',
            'keywords' => ['tahun ajaran aktif', 'semester aktif', 'aktifkan', 'ganjil', 'genap'],
        ],
        [
            'category' => 'Tahun Ajaran',
            'question' => 'Perbedaan semester ganjil dan genap',
            'answer' => 'Semester ganjil dan genap menyimpan data kerja terpisah. Nilai, absensi, catatan, capaian, ekstrakurikuler, dan rapor harus dicek sesuai semester aktif.',
            'keywords' => ['semester', 'ganjil', 'genap', 'nilai', 'absensi', 'rapor'],
        ],
        [
            'category' => 'Data Siswa',
            'question' => 'Kenapa data siswa tidak muncul',
            'answer' => 'Biasanya siswa belum memiliki enrollment pada tahun ajaran dan semester aktif. Cek kelas siswa, semester aktif, dan hasil import atau kenaikan kelas.',
            'keywords' => ['siswa tidak muncul', 'data siswa', 'enrollment', 'kelas', 'semester', 'tahun ajaran'],
        ],
        [
            'category' => 'Template Rapor',
            'question' => 'Cara mengelola template rapor',
            'answer' => 'Buka Admin > Format Rapor. Upload template sesuai jenis rapor, kelas, dan tahun ajaran, lalu aktifkan template yang akan dipakai.',
            'keywords' => ['template rapor', 'format rapor', 'docx', 'pdf', 'upload template', 'aktifkan'],
        ],
        [
            'category' => 'Template Rapor',
            'question' => 'Kenapa PDF atau DOCX rapor belum tersedia',
            'answer' => 'Biasanya template aktif belum tersedia untuk kelas, jenis rapor, atau tahun ajaran yang dipilih. Cek template rapor dan pastikan data rapor sudah lengkap.',
            'keywords' => ['pdf', 'docx', 'rapor', 'template', 'download', 'preview', 'tidak tersedia'],
        ],
        [
            'category' => 'Tahun Ajaran',
            'question' => 'Cara memulai semester baru',
            'answer' => 'Gunakan menu Tahun Ajaran setelah semester ganjil selesai. Pastikan data ganjil sudah dicek, lalu lanjutkan ke semester genap agar struktur siap dipakai.',
            'keywords' => ['semester baru', 'lanjut semester', 'ganjil', 'genap', 'tahun ajaran'],
        ],
        [
            'category' => 'Kenaikan Kelas',
            'question' => 'Cara kenaikan kelas',
            'answer' => 'Kenaikan kelas dilakukan setelah semester genap selesai dan tahun ajaran berikutnya dibuat. Buka Kenaikan Kelas, cek siswa, lalu proses ke kelas tujuan.',
            'keywords' => ['kenaikan kelas', 'promosi', 'tahun ajaran berikutnya', 'kelas tujuan', 'lulus'],
        ],
        [
            'category' => 'Keamanan Data',
            'question' => 'Apa yang tidak boleh dihapus jika sudah ada data nilai',
            'answer' => 'Jangan hapus permanen tahun ajaran, kelas, siswa, atau mapel yang sudah memiliki nilai atau riwayat. Arsipkan saja, atau minta prosedur khusus ke pengelola sistem.',
            'keywords' => ['hapus', 'hapus permanen', 'nilai', 'riwayat', 'arsip', 'recycle bin'],
        ],
        [
            'category' => 'Rapor',
            'question' => 'Cara mengecek kelengkapan data sebelum rapor',
            'answer' => 'Cek dashboard, input nilai, absensi, catatan, capaian, ekstrakurikuler, dan template rapor. Pastikan semuanya sesuai tahun ajaran dan semester aktif.',
            'keywords' => ['kelengkapan rapor', 'rapor lengkap', 'dashboard', 'nilai', 'absensi', 'catatan', 'template'],
        ],
        [
            'category' => 'Arsip',
            'question' => 'Cara melihat data yang sudah diarsipkan atau recycle bin',
            'answer' => 'Buka menu Recycle Bin atau data arsip yang tersedia. Gunakan restore jika data masih diperlukan, dan hindari hapus permanen jika sudah memiliki riwayat.',
            'keywords' => ['recycle bin', 'arsip', 'restore', 'hapus permanen', 'data diarsipkan'],
        ],
    ],

    'pengajar' => [
        [
            'category' => 'Nilai',
            'question' => 'Cara input nilai',
            'answer' => 'Buka Pengajar > Data Nilai Pelajaran, pilih mapel, lalu isi nilai siswa. Pastikan LM dan TP sudah tersedia sebelum menyimpan nilai.',
            'keywords' => ['input nilai', 'nilai', 'tp', 'lm', 'simpan', 'mapel', 'siswa'],
        ],
        [
            'category' => 'Nilai',
            'question' => 'Kenapa siswa tidak muncul di input nilai',
            'answer' => 'Biasanya siswa belum terdaftar di kelas mapel pada semester aktif. Cek tahun ajaran, semester, dan kelas mapel; jika masih kosong hubungi admin.',
            'keywords' => ['siswa tidak muncul', 'input nilai', 'enrollment', 'kelas', 'semester', 'tahun ajaran'],
        ],
        [
            'category' => 'Mata Pelajaran',
            'question' => 'Kenapa mata pelajaran tidak muncul',
            'answer' => 'Biasanya guru belum ditugaskan ke mapel tersebut atau konteks tahun ajaran berbeda. Cek role pengajar dan hubungi admin untuk assignment mapel.',
            'keywords' => ['mapel tidak muncul', 'mata pelajaran', 'pengajar', 'assignment', 'tahun ajaran'],
        ],
        [
            'category' => 'Nilai',
            'question' => 'Kenapa nilai tidak bisa disimpan',
            'answer' => 'Biasanya ada nilai yang belum valid, siswa tidak sesuai kelas mapel, atau LM/TP belum lengkap. Periksa pesan validasi, lalu simpan ulang.',
            'keywords' => ['nilai tidak bisa disimpan', 'gagal simpan', 'validasi', 'tp', 'lm', 'kelas'],
        ],
        [
            'category' => 'TP dan LM',
            'question' => 'Cara membuat Lingkup Materi',
            'answer' => 'Buka menu Mata Pelajaran, pilih mapel, lalu tambah Lingkup Materi. Buat materi yang mewakili kelompok pembelajaran utama.',
            'keywords' => ['lingkup materi', 'lm', 'buat lm', 'mata pelajaran', 'materi'],
        ],
        [
            'category' => 'TP dan LM',
            'question' => 'Cara membuat Tujuan Pembelajaran',
            'answer' => 'Buka mapel dan Lingkup Materi, lalu tambah Tujuan Pembelajaran. Pastikan TP jelas karena nilai siswa diisi berdasarkan TP tersebut.',
            'keywords' => ['tujuan pembelajaran', 'tp', 'buat tp', 'lm', 'nilai'],
        ],
        [
            'category' => 'Progress',
            'question' => 'Apa arti progress nilai 0%',
            'answer' => 'Progress 0% berarti belum ada nilai lengkap pada konteks semester aktif, atau LM/TP belum siap. Cek siswa, TP, LM, dan nilai akhir rapor.',
            'keywords' => ['progress 0', 'progress nilai', '0%', 'nilai', 'tp', 'lm', 'semester'],
        ],
        [
            'category' => 'Progress',
            'question' => 'Kenapa progress belum 100%',
            'answer' => 'Biasanya masih ada siswa, TP/LM, atau nilai akhir yang belum lengkap. Buka mapel terkait, cek daftar siswa, lalu lengkapi nilai yang kosong.',
            'keywords' => ['progress', 'belum 100', 'nilai belum lengkap', 'nilai akhir', 'siswa'],
        ],
        [
            'category' => 'Nilai',
            'question' => 'Cara mengubah nilai yang salah',
            'answer' => 'Buka kembali halaman input nilai untuk mapel tersebut, perbaiki nilai, lalu simpan. Pastikan perubahan dilakukan pada semester yang benar.',
            'keywords' => ['ubah nilai', 'edit nilai', 'nilai salah', 'simpan nilai', 'semester'],
        ],
        [
            'category' => 'Nilai',
            'question' => 'Cara melihat nilai yang sudah diinput',
            'answer' => 'Buka daftar nilai atau preview nilai pada mapel. Data yang tampil mengikuti tahun ajaran dan semester aktif.',
            'keywords' => ['lihat nilai', 'preview nilai', 'nilai sudah diinput', 'mapel', 'semester'],
        ],
        [
            'category' => 'TP dan LM',
            'question' => 'Apa yang dilakukan jika TP atau LM belum tersedia',
            'answer' => 'Buat Lingkup Materi dan Tujuan Pembelajaran terlebih dahulu. Jika menu tidak tersedia atau mapel tidak muncul, hubungi admin.',
            'keywords' => ['tp belum tersedia', 'lm belum tersedia', 'buat tp', 'buat lm', 'admin'],
        ],
        [
            'category' => 'Role',
            'question' => 'Cara ganti role jika guru juga wali kelas',
            'answer' => 'Gunakan dropdown profil untuk berpindah role. Jika pilihan role tidak muncul, berarti assignment pengajar atau wali belum lengkap.',
            'keywords' => ['ganti role', 'role', 'pengajar', 'wali kelas', 'dropdown profil'],
        ],
        [
            'category' => 'Akses',
            'question' => 'Kenapa akses ditolak',
            'answer' => 'Biasanya role yang dipilih tidak sesuai atau guru tidak ditugaskan pada mapel tersebut. Cek role aktif, lalu hubungi admin jika assignment perlu diperbaiki.',
            'keywords' => ['akses ditolak', 'forbidden', '403', 'role', 'assignment', 'mapel'],
        ],
        [
            'category' => 'Bantuan',
            'question' => 'Kapan perlu hubungi admin',
            'answer' => 'Hubungi admin jika siswa, kelas, mapel, TP/LM, atau role tidak muncul meskipun semester aktif sudah benar.',
            'keywords' => ['hubungi admin', 'bantuan', 'siswa tidak muncul', 'mapel tidak muncul', 'role'],
        ],
    ],

    'wali_kelas' => [
        [
            'category' => 'Siswa',
            'question' => 'Cara melihat daftar siswa',
            'answer' => 'Buka Wali Kelas > Siswa. Daftar siswa mengikuti kelas wali, tahun ajaran, dan semester aktif.',
            'keywords' => ['daftar siswa', 'siswa', 'wali kelas', 'kelas wali', 'semester'],
        ],
        [
            'category' => 'Siswa',
            'question' => 'Kenapa siswa wali kelas tidak muncul',
            'answer' => 'Biasanya siswa belum masuk enrollment kelas wali pada semester aktif. Cek tahun ajaran dan semester, lalu hubungi admin jika kelas siswa perlu diperbaiki.',
            'keywords' => ['siswa tidak muncul', 'wali kelas', 'enrollment', 'kelas', 'semester', 'admin'],
        ],
        [
            'category' => 'Absensi',
            'question' => 'Cara mengisi absensi',
            'answer' => 'Buka Wali Kelas > Absensi, isi sakit, izin, dan tanpa keterangan untuk tiap siswa, lalu simpan. Absensi tersimpan per semester.',
            'keywords' => ['absensi', 'sakit', 'izin', 'alpha', 'tanpa keterangan', 'semester'],
        ],
        [
            'category' => 'Catatan',
            'question' => 'Cara mengisi catatan siswa',
            'answer' => 'Buka menu Catatan Siswa, pilih siswa, isi catatan singkat, lalu simpan. Pastikan semester aktif sudah sesuai.',
            'keywords' => ['catatan siswa', 'catatan', 'wali kelas', 'simpan', 'semester'],
        ],
        [
            'category' => 'Catatan',
            'question' => 'Cara mengisi catatan mata pelajaran',
            'answer' => 'Buka Catatan Mata Pelajaran, pilih mapel dan siswa, lalu isi catatan. Catatan ini mengikuti mapel, tahun ajaran, dan semester aktif.',
            'keywords' => ['catatan mata pelajaran', 'catatan mapel', 'mapel', 'siswa', 'semester'],
        ],
        [
            'category' => 'Ekstrakurikuler',
            'question' => 'Cara mengisi ekstrakurikuler',
            'answer' => 'Buka Wali Kelas > Ekstrakurikuler, pilih kegiatan, isi nilai atau deskripsi, lalu simpan. Data semester genap tidak mengambil data ganjil.',
            'keywords' => ['ekstrakurikuler', 'nilai ekstra', 'kegiatan', 'semester', 'ganjil', 'genap'],
        ],
        [
            'category' => 'Capaian',
            'question' => 'Cara mengisi capaian kompetensi',
            'answer' => 'Buka Capaian Kompetensi, pilih mapel, lalu isi capaian untuk siswa yang tersedia. Pastikan nilai akhir mapel sudah lengkap jika capaian diambil dari nilai.',
            'keywords' => ['capaian kompetensi', 'capaian', 'nilai akhir', 'mapel', 'siswa'],
        ],
        [
            'category' => 'Rapor',
            'question' => 'Cara preview rapor',
            'answer' => 'Buka Wali Kelas > Rapor, pilih siswa dan jenis rapor, lalu gunakan preview. Cek data sebelum download atau cetak.',
            'keywords' => ['preview rapor', 'rapor', 'preview', 'download', 'cetak', 'wali'],
        ],
        [
            'category' => 'Rapor',
            'question' => 'Kenapa rapor belum lengkap',
            'answer' => 'Biasanya masih ada nilai, absensi, catatan, capaian, ekstrakurikuler, atau template yang belum lengkap. Cek dashboard dan data pendukung.',
            'keywords' => ['rapor belum lengkap', 'rapor', 'nilai', 'absensi', 'catatan', 'capaian', 'ekstrakurikuler'],
        ],
        [
            'category' => 'Rapor',
            'question' => 'Kenapa PDF atau DOCX belum bisa diunduh',
            'answer' => 'Biasanya template aktif belum tersedia atau data rapor belum lengkap. Untuk PDF, server juga harus mendukung konversi dokumen.',
            'keywords' => ['pdf', 'docx', 'download', 'rapor', 'template', 'konversi dokumen'],
        ],
        [
            'category' => 'Rapor',
            'question' => 'Kenapa nilai siswa belum muncul di rapor',
            'answer' => 'Biasanya nilai mapel belum lengkap atau belum tersimpan pada semester aktif. Minta pengajar mengecek input nilai dan progress mapel.',
            'keywords' => ['nilai belum muncul', 'rapor', 'input nilai', 'pengajar', 'progress', 'semester'],
        ],
        [
            'category' => 'Rapor',
            'question' => 'Cara mengecek data sebelum cetak rapor',
            'answer' => 'Cek nilai, absensi, catatan, capaian, ekstrakurikuler, dan template rapor. Gunakan preview untuk memastikan data sudah benar sebelum cetak.',
            'keywords' => ['cek data rapor', 'cetak rapor', 'preview', 'nilai', 'absensi', 'template'],
        ],
        [
            'category' => 'Siswa',
            'question' => 'Apa yang harus dilakukan jika ada siswa salah kelas',
            'answer' => 'Jangan ubah data sendiri jika tidak ada menu yang sesuai. Hubungi admin agar enrollment kelas siswa diperbaiki pada tahun ajaran dan semester yang benar.',
            'keywords' => ['siswa salah kelas', 'kelas salah', 'enrollment', 'hubungi admin', 'semester'],
        ],
        [
            'category' => 'Bantuan',
            'question' => 'Kapan perlu hubungi admin',
            'answer' => 'Hubungi admin jika siswa, mapel, template rapor, PDF/DOCX, atau akses wali tidak muncul meskipun tahun ajaran dan semester sudah benar.',
            'keywords' => ['hubungi admin', 'bantuan', 'akses', 'template', 'pdf', 'docx', 'siswa'],
        ],
    ],
];
